### ISSUE TITLE
watcher compatible post-run callbacks

### ISSUE THREAD

**Issue by ackagel** [angelolab/toffy#102]
### **Relevant background**

> Give a brief (1-2 paragraph) description of the problem/issue that this feature is solving, and how it addresses the issue

Right now, no run callbacks are implemented.  Further, even if run callbacks were implemented, users would need to be careful to execute run-callbacks' requisite per-fov callbacks.  Users are generally unconcerned with per-fov callbacks; they're much more interested in the post-run outputs (i.e run-callbacks).  Therefore, requiring user interaction with per-fov callback specification is not ideal.

## **Design overview**

> Describe each of the main components of the proposed project

Similar to the per-fov architecture, there will be a `RunCallbacks` object.  However, the `RunCallbacks` object will not initially cache data for other run callbacks to use, since each run callback will only depend on fov callbacks.  If necessary, the `RunCallbacks` object could be passed to `FovCallbacks` objects to directly retrieve data outputs (as opposed to reading a file), but I can't immediately think of a case where this would be explicitly ideal, with no risk of running out of memory.

Rather than adding `build_run_callbacks` function, there will be a single `build_callbacks` function which will handle the construction of _both_ the per-fov callbacks and the per-run callbacks.  This function will primarily accept run callback names, and will deduce the requisite fov callbacks from a constant dictionary e.g:

```
RUN_PREREQUISITES = {
    'plot_qc_metrics': {'generate_qc'},
    'stitch_images': {'extract_tiffs'},
    'mph_normalize_images': {'extract_tiffs', 'compute_mph'},
    ...
}
```

There will be also be an argument for setting additional per-fov callbacks, defaulted to `('extract_tiffs',)`.

## **Design list/flowchart**

> Provide an overview of how the different pieces of the project will interact with each other, either in a numbered list, bullet point, or brief sketch

Largely described above.  In terms of user interface, `start_watcher` will no longer take lists of multiple callbacks, since the chaining makes the need for multiple per-fov (and per-run) callbacks pointless.

### **Required inputs**

> Provided a description of the required inputs for this project, including column names for dfs, dimensions for image data, prompts for user input, etc

Pretty much the same as before.  Only difference is that per-fov callbacks won't typically need to be specified, since they're deduced from the specified per-run callbacks.

### **Output files**

> Provide a description of the outputs for this project, including column names for dfs, dimensions for image data, etc. If any plots will be generated, provide (simple) sketches demonstrating the plot type and axes labels. 

This will only generate plots/outputs that already exist in toffy.

## **Section 2: Implementation details**

See above

**Comment by ackagel** [comment]
@ngreenwald updated the doc

**Comment by ngreenwald** [comment]
Great, makes sense. Can you add a timeline? Looks good to go

**Comment by ackagel** [comment]
Should be ready for review by Tuesday at the latest.  Framework should be largely in place by end of today + maybe some of the qc plotting callback.  Giving myself Monday and Tuesday for clean up + extra callbacks I might be forgetting about (streak detection, image stitching, etc.).

Side note, we should hash out how we want to deal with image correcting functions (streaks, mph norming, rosetta, etc), in terms of whether they're per-fov corrections or per-run corrections, what order to chain them in, whether to put them in all in one big, option heavy 'post-processing' callback, saving each one's output in a different directory, etc.

**Comment by ngreenwald** [comment]
Sounds good. I think now that we'll have an example fov-level callback and an example run-level callback (qc metrics plotting), all of the additional massaging to get the other functions integrated can get passed on to someone else

My current thinking is that each of those would be FOV-level, but I don't have a strong preference
