### ISSUE TITLE
Helper function for MPH histogram plots

### ISSUE THREAD

**Issue by camisowers** [angelolab/toffy#106]
*This is for internal use only; if you'd like to open an issue or request a new feature, please open a bug or enhancement issue*

**Section 1: Design details**

**Relevant background**

Addresses #75.
Create a single helper function to generate the MPH histograms. This functionality currently exists in the [compute_pulse_heights](https://github.com/angelolab/toffy/blob/main/templates/compute_pulse_heights.ipynb) notebook. 

**Design overview**

There will be one encompassing function `vizualize_mph_hist()` which combines the other functions for retrieving and calculating the data.
To examine the data, I can move the `bin_array()` function defined in the notebook to either `mibi_bin_tools.bin_files` (would require another branch/PR) or temporarily to `mph_compy.py` while working on this and then move it later if needed.

**Design list/flowchart**

```
def bin_array(arr, bin_factor):
    arr_bin = np.cumsum(arr)
    arr_bin[bin_factor:] = arr_bin[bin_factor:] - arr_bin[:-bin_factor]
    arr_bin = arr_bin[bin_factor::bin_factor]
    
    return arr_bin
```

```
def compute_mph_intensities(base_dir, fov_list, bin_factor=100):
     if os.path.exists(os.path.join(base_dir, 'mph_counts.csv')):
          return

     # visualize all fovs in folder if list not specified
     if fov_list is None:
          fov_list = io_utils.remove_file_extensions(io_utils.list_files(base_dir, substrs='.bin'))
    
     for fov in fov_list:
           _, intensities, pulse_counts = bin_files.get_histograms_per_tof(data_dir, fov, channel, panel)
    
           int_bin = np.cumsum(intensities) / intensities.sum()
           median = (np.abs(int_bin - 0.5)).argmin()
    
           out_df.append({
               'fov': fov,
               'all_intensities': intensities,
               'all_pulse_counts': pulse_counts,
               'median_intensity': median,
          })

     final_df['binned_intensities'] = final_df['all_intensities'].apply(lambda x: bin_array(x, bin_factor))

     final_df = pd.DataFrame(out_df)
     final_df.to_csv(os.path.join(base_dir, 'mph_counts.csv'))
```

```
def vizualize_mph_hist(base_dir, fov_list=None, bin_factor=100, x_cutoff=20000, normalize=True):
     compute_mph_intensities(base_dir, fov_list, bin_factor)
     data = pd.read_csv(os.path.join(base_dir, 'mph_counts.csv'))
     # matplotlib fun
          for idx, row in data.iterrows():
               if normalize:
                    plt.plot(np.arange(row['binned_intensities'].shape[0])[0:x_cutoff//bin_factor]*bin_factor, row['binned_intensities'] 
                                [0:x_cutoff//bin_factor] / np.max(row))
               else:
                    plt.plot(np.arange(row['binned_intensities'].shape[0])[0:x_cutoff//bin_factor]*bin_factor, row['binned_intensities'] 
                                [0:x_cutoff//bin_factor])
```

**Required inputs**

Need a directory where the bin files are stored and (optional) user specification for fov_list (with format 'fov-1-scan-1' for each item in the list), bin_factor, and x_cutoff. 

**Output files**

Will output a csv with the mph data for all FOVs and visualize the plots. 

**Section 2: Implementation details**

**Control flow**

Provide additional, more granular details (if necessary) about how the proposed coding logic will be put together

**Milestones and timeline**

5/25 - 6/2: Helper functions and Notebook updates
6/10: finish revisions and tests

**Comment by ngreenwald** [comment]
Awesome start, glad we decided to do a design doc. 
1. This function only needs to generate the histogram plots, not the MPH vs voltage stuff at the top:
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/13770365/169619115-daec5f1a-b31b-4e45-a8d3-644451b00000.png">
2. The moly run stuff is old, we don't need separate logic to support it. We can have a single function that takes in a list of FOVs, all in the same folder, and generates the plot. 

3. There should be a function arg that controls whether the histograms are normalized or not. Here's adam's code that does the normalization (just dividing each row by the max) 

`plt.plot(np.arange(int_bin.shape[0])[0:20000//bin_factor]*bin_factor,int_bin[0:20000//bin_factor]) / np.max(int_bin))`

Check with @ackagel to see if this is still the preferred way to generate the histograms, or if something else in mibi_bin_tools would be better. Once you've checked with him and updated the doc, let me know and I'll take a look

**Comment by camisowers** [comment]
@ngreenwald Updated! I edited `visualize mph_hist` to have an argument for normalizing, as well as default bin_factor and x_cutoff arguments per Adam's suggestion. I also added the `binned_intensities` values to the `compute_mph_intensities` function, which can now also take in a fov_list provided by the user in the second function.

**Comment by ngreenwald** [comment]
Looks good
