### ISSUE TITLE
Refactor components of `4_compensate_image_data.ipynb` to `rosetta.py`

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/toffy#116]
**Is your feature request related to a problem? Please describe.**

The image compensation notebook currently has a lot of loops and processes specified directly in the notebook. This can be abstracted away to reduce the amount of code visible to the user.

**Describe the solution you'd like**

The functionality can be moved to `rosetta.py`.

**Comment by ngreenwald** [comment]
Addressed by #212
