### ISSUE TITLE
Add helper function for reading and writing json files

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/toffy#129]
**Is your feature request related to a problem? Please describe.**
We have a couple places in the codebase where we reuse the sample context manager for reading and writing jsons.

**Describe the solution you'd like**
We should create dedicated helper functions that peform these actions, as well as sanity checking the paths.

**Comment by mheskett** [comment]
To confirm, a wrapper for 
`         with open(json_path, 'r') as jp:
            json_file = json.load(jp)`
and 
`        with open(json_path, 'w') as jp:
            json.dump(tissue_json, jp)`
that implements validate_paths() is whats needed? Should this go into json_utils.py or a new file?

**Comment by ngreenwald** [comment]
Yup exactly. `json_utils` is perfect. And then replace all the instances of the original code in the codebase and the notebooks with the new function
