### ISSUE TITLE
default image format for optical image exported by MIBIscope does not match 

### ISSUE THREAD

**Issue by HPiyadasa** [angelolab/toffy#135]
**Describe the bug**
Optical images downloaded from the MIBIscope are png. The 2_create_tma_mibi_run notebook requires the optical image to be a bmp since the last update. 

**Expected behavior**
Change required format for the notebook to the default png format exported by the MIBIscope.

**Comment by ngreenwald** [comment]
P9 is still creating .bmp files @HPiyadasa, is this a M13-specific issue?
