### ISSUE TITLE
Toffy environment won't build

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/toffy#140]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
The current toffy environment fails to build, due to the MIBI-bin-tools update from yesterday. We need to pin mibi-bin-tools to the previous version until we update the requirements

**Comment by srivarra** [comment]
I thought the issue was with ark-analysis' versioning? This is a different?
