### ISSUE TITLE
Helper function to split run json into smaller files

### ISSUE THREAD

**Issue by camisowers** [angelolab/toffy#144]
*This is for internal use only; if you'd like to open an issue or request a new feature, please open a bug or enhancement issue*

**Section 1: Design details**

**Relevant background**

Closes #82. Create a new helper function in `json_utils.py` that will split the run json into smaller files for imaging.

**Design overview**

If provided a run_json with 10 fovs and list [4,3,3], will produce 3 new jsons.
* run_json_part1 = [fov1, fov2, fov3, fov4]
* run_json_part2 = [fov5, fov6, fov7,]
* run_json_part3 = [fov8, fov9, fov10]

The function will raise an error if the list does not sum to the number of fovs given in a run file.

```
def split_run_file(tma_dir, run_file_name, file_split: List):
    json_path = os.path.join(tma_dir, run_file_name)
    full_json = read_json_file(json_path, encoding='utf-8')

    # check list is valid FOV split
    if not sum(file_split)==len(full_json['fovs']):
        raise ValueError("Sum of the provided list does not match the number of FOVs in the run file.")
    
    # split the run json into smaller files
    start=0
    for i in len(file_split):
        json_i = copy.deepcopy(full_json)
        stop = start+file_split[i]
        json_i['fovs'] = json_i['fovs'][start:stop]
        start = start+file_split[i]

        save_path = os.path.join(tma_dir, run_file_name.split('.json')[0] + '_part' + str(i+1) + '.json)
        json_utils.write_json_file(save_path, json_i, encoding='utf-8')

```

Will be implemented in [2_create_tmab_mibi_run notebook](https://github.com/angelolab/toffy/blob/ac80af8ddca601ce91065de60bb2be4d70171262/templates/2_create_tma_mibi_run.ipynb).

**Required inputs**

* path to tma directory
* name of the run json file
* list detailing how many fovs will be in each new json file, i.e. [12, 12, 10]

**Output files**

Specified number of new json files. 

**Section 2: Implementation details**

Once you have completed section 1, please tag the relevant parties and iterate on the initial design details until everyone is satisfied. Then, 
proceed to section 2

**Control flow**

Provide additional, more granular details (if necessary) about how the proposed coding logic will be put together

**Milestones and timeline**

List each of the major components of the project, and provide an estimated completion date for each one.

**Comment by camisowers** [comment]
@ngreenwald

**Comment by ngreenwald** [comment]
Looks good. We should add this to both the create_tiled_mibi_run and create_tma_mibi run.

This can be imported from json_utils, with a final cell at the bottom of the notebook explaining how this function can be used. Make sure to update the variable names in the function to be more general since it won't just be the tma notebook.
