### ISSUE TITLE
QC metrics plots for control samples in tissue microarray 

### ISSUE THREAD

**Issue by mheskett** [angelolab/toffy#149]
**Section 1: Design details**

**Relevant background**
Plot the consistency of expression of all markers within the control tissues over time using the non-zero mean intensity and/or the 99.9th percentile intensity. The purpose is to detect any possible systematic bias to the control signals throughout the imaging run.

**Design overview**
The input will consist of data from multiple TMAs, each TMA with a set of controls, some of which will be shared across TMAs. The program will read data from all TMAs, identify control samples for each TMA, extract the data from each control sample and perform QC metrics of choice. Violin plots will be produced in a faceted grid for each marker 

![IMG_1836](https://user-images.githubusercontent.com/11022774/179868297-716a4bad-842a-4bf7-bb6b-2b8b0dc1ce6a.jpg)

**Design list/flowchart**

Provide an overview of how the different pieces of the project will interact with each other, either in a numbered list, bullet point, or brief sketch

**Required inputs**
Images for marker expression for multiple spots on two or more TMAs including control tissue and tumor tissue. Control tissue names will also be given as an input.

**Output files**
Violin plots of control expression across multiple TMAs and whichever tissues are included as controls

@ngreenwald 

**Section 2: Implementation details**

Once you have completed section 1, please tag the relevant parties and iterate on the initial design details until everyone is satisfied. Then, 
proceed to section 2

**Control flow**

Provide additional, more granular details (if necessary) about how the proposed coding logic will be put together

**Milestones and timeline**

List each of the major components of the project, and provide an estimated completion date for each one.

**Comment by ngreenwald** [comment]
Looks good, two quick questions:

1. Can you add a rough doodle/sketch of what the plots will actually look like? What would the axes be, what will be faceted and what will be plotted, etc. 
2. How are the control tissues going to be identified? The current description makes it sound like all of the data is going to be read in then it will automatically be determined. I think it makes more sense to have the user provided a list of control tissues, which are then used to find substring matches to identify the relevant folders, and only those folders are read in/processed
