### ISSUE TITLE
Calculate cell density only in image regions that contain cells

### ISSUE THREAD

**Issue by mheskett** [angelolab/toffy#150]
**Section 1: Design details**

**Relevant background**
Each image may or may not have cells fully populating the entire field of view. For example needle biopsies may have a narrow region of tissue and empty space for some of the image. To accurately calculate cell density we must first identify regions of each image that contain cells and ignore regions of the image that have no cells. The purpose of this project is to figure out which channels or combinations of channels provides the best input data to perform identification of cell dense vs empty regions.

**Design overview**
Pick channels and identify cell dense vs empty regions and optimize for the best fit. We will either use an optimization strategy where a test set is created manually and an area of error is minimized, or we will just try a bunch of different channels and then visually inspect the results and make a qualitative decision. 

Describe each of the main components of the proposed project
@ngreenwald 
**Design list/flowchart**

Provide an overview of how the different pieces of the project will interact with each other, either in a numbered list, bullet point, or brief sketch

**Required inputs**

Provided a description of the required inputs for this project, including column names for dfs, dimensions for image data, prompts for user input, etc

**Output files**

Provide a description of the outputs for this project, including column names for dfs, dimensions for image data, etc. If any plots will be generated, 
provide (simple) sketches demonstrating the plot type and axes labels. 

**Section 2: Implementation details**

Once you have completed section 1, please tag the relevant parties and iterate on the initial design details until everyone is satisfied. Then, 
proceed to section 2

**Control flow**

Provide additional, more granular details (if necessary) about how the proposed coding logic will be put together

**Milestones and timeline**

List each of the major components of the project, and provide an estimated completion date for each one.

**Comment by ngreenwald** [comment]
The first part of this is spot on about the motivation. However, the issue isn't that the segmentation is inaccurate in dense vs empty areas; rather, we simply want an automated way of identifying where the empty areas of the image are. 

So the purpose of this PR would be to create an automated method to identify regions of an image that we would never expect to have cells, because there's no actual tissue present. Then, we would create a mask outlining those empty areas, which can use to compute the area in the image that has the potential of containing cells. We can use that area to normalize the number of cells, getting a density. 

Segmentation is totally separate from this. We're not trying to optimize the segmentation, we're trying to figure out how much real estate we have to work with in a given image. Does that make sense?

**Comment by cliu72** [comment]
Hi Michael! Here is some example code Noah asked me to share where I used a gold mask to determine tissue density. Hopefully it's straight forward, but please let me know if you have any questions.

Generate histograms for all FOVs to find a threshold:
```
import matplotlib.pyplot as plt
import numpy as np
import os
import skimage.io as io
from scipy.ndimage import gaussian_filter

all_fovs = os.listdir("/home/canda/hadeesha_cimac/single_channel/")

fig = plt.figure(figsize=(10,30))
for i,fov in enumerate(all_fovs):
    ax = plt.subplot(15,4,i+1)
    tif_path = os.path.join("/home/canda/hadeesha_cimac/single_channel",fov,"Au.tiff")
    tif_array = np.array(io.imread(tif_path))
    dat = tif_array.flatten()
    plt.hist(dat[dat>0], bins=100)
    plt.ylim([0,100000])
    plt.axvline(2500, color='red', linestyle='dashed', linewidth=1) #change this number to test different thresholds
    plt.title(fov)

plt.tight_layout()
plt.show()
```

Histograms look something like this:
![image](https://user-images.githubusercontent.com/11382352/184024756-4779f8ed-29f8-4e63-8bf9-5f37c1e2c4ad.png)


Look at specific FOVs:
```
%matplotlib notebook

# Look at gold
fov = "R6C5"
tif_path = os.path.join("/home/canda/hadeesha_cimac/single_channel",fov,"Au.tiff")
tif_array = np.array(io.imread(tif_path))

plt.figure(figsize=(10,10))
plt.imshow(tif_array, cmap='gray')
plt.axis('off')`
```

```
# Look at binarized image
plt.figure(figsize=(10,10))
new_array = np.zeros(tif_array.shape)
new_array[np.where(tif_array > 2500)] = 1 # Change this number to test thresholds
plt.imshow(new_array, cmap='gray')
plt.show()
```

Create mask for all FOVs (once a threshold has been chosen):
```
import pandas as pd
from skimage import img_as_uint

cutoff = 2500
all_fovs = os.listdir("/home/canda/hadeesha_cimac/single_channel/")
output_dir = "/home/canda/hadeesha_cimac/gold_masks/"

if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Get gold mask of all images
all_px_dict = {}
gold_px_dict = {}
for fov in all_fovs:
    tif_path = os.path.join("/home/canda/hadeesha_cimac/single_channel",fov,"Au.tiff")
    tif_array = np.array(io.imread(tif_path))
    new_array = np.zeros(tif_array.shape)
    new_array[np.where(tif_array > cutoff)] = 1
    io.imsave(os.path.join(output_dir, fov+"_gold.tiff"), img_as_uint(new_array))
    
    x,y = tif_array.shape
    all_px_dict[fov] = x*y
    gold_px_dict[fov] = np.sum(new_array)


# Save data
all_px_df = pd.DataFrame.from_dict(all_px_dict, orient='index', columns=['all_px'])
gold_px_df = pd.DataFrame.from_dict(gold_px_dict, orient='index', columns=['all_gold'])
merge_df = all_px_df.merge(gold_px_df, left_index=True, right_index=True)
merge_df['tissue_area'] = (merge_df['all_px'] - merge_df['all_gold']) / merge_df['all_px']
merge_df.to_csv("/home/canda/hadeesha_cimac/tissue_area.csv", index_label='fov')

```

**Comment by ngreenwald** [comment]
Added to my own project, will incorporate if others need to use it
