### ISSUE TITLE
Improving documentation throughout Toffy

### ISSUE THREAD

**Issue by srivarra** [angelolab/toffy#157]
*This is for internal use only; if you'd like to open an issue or request a new feature, please open a bug or enhancement issue*

**Section 1: Design details**

**Relevant background**

The documentation for each notebook is lacking in some combination, or all of the following aspects:

1. _What_ background information is necessary?
2. _Why_ are we running a certain step? 
3. _How_ will this process solve a certain problem or issue?
4. _What is the significance_ of the actions we are taking?
5. _What is the next step_ to do if applicable?

This brings up many questions, and for those who are using the MIBI for the first time it can be quite confusing and unintuitive. 

In addition we need to let the user know where to get the panels needed from the Ionpath MIBItracker, and how to make adjustments so they are valid for ingest.

The following design document contains modifications for each notebook. The reference document is available [here](https://docs.google.com/document/d/1ublUuTe3-HqAmYhm_nZO8VL2G8thNNA9DvcCXr-tsQM/edit?usp=sharing).

[**Link to the Github Project logging the progress**](https://github.com/orgs/angelolab/projects/5/)

**Design overview**

We will be pruning through each notebook in Toffy, adding descriptions and images to help:

1. Explain certain code-blocks
2. What necessary files should look like
3. Describe what adjusting certain arguments will do and why someone would want to change them
4. Potentially add a FAQ section at the end of each notebook

**Design list/flowchart**

Links to each Issue outlining adjustments to make for each notebook, and miscellaneous documentation improvements.

1. #158
2. #159
3. #160
4. #161
5. #163
6. #164

**Required inputs**

N/A

**Output files**

N/A

**Section 2: Implementation details**

Once you have completed section 1, please tag the relevant parties and iterate on the initial design details until everyone is satisfied. Then, 
proceed to section 2

**Control flow**

Provide additional, more granular details (if necessary) about how the proposed coding logic will be put together

**Milestones and timeline**

List each of the major components of the project, and provide an estimated completion date for each one.

**Comment by srivarra** [comment]
@camisowers @alex-l-kong @ngreenwald Let me know your thoughts and what suggestions you guys may have.

**Comment by ngreenwald** [comment]
Agreed, I think this will be super useful

**Comment by camisowers** [comment]
I'll have to go through the notebooks to update the panel descriptions after dealing with issue #168, so maybe just include links to the example file for now and I'll add more informative panel documentation later.
