### ISSUE TITLE
Typo in argument passed to normalize_image_data

### ISSUE THREAD

**Issue by efrancis28** [angelolab/toffy#165]
In the notebook for step 4b (normalization) the final code block makes a call to normalize_image_data. One of the arguments passed in is 'pulse_heights_dir' however the function in normalize.py is expecting 'pulse_height_dir' sans 's.' Very minor.

**Comment by ngreenwald** [comment]
Cool, wanna open a PR to fix it? You can create a new branch, make the change, commit the change, then push the branch here. Could be good practice using github. If not no worries, @srivarra can handle it.

**Comment by efrancis28** [comment]
Good idea, I will do that.

Erin
________________________________
