### ISSUE TITLE
FFC chan_39 check 

### ISSUE THREAD

**Issue by camisowers** [angelolab/toffy#167]
**Is your feature request related to a problem? Please describe.**
Rosetta requires the user's panel to include `chan_39` and without will cause `compensate_image_data()` to not run.

**Describe the solution you'd like**
In general, we should make sure than every channel in the compensation matrix being used is included in the panel at the beginning of the noteboook (before extracting our ~10 fovs to test rosetta on).
Create a helper function which gives an error if panel and comp matrix do not align, and run when the panel name is provided.

**Comment by ngreenwald** [comment]
In addition, we need to figure out why the rosetta matrix that Marte was using didn't load the column corresponding to channel_39 correctly, but I've had no issues with this before
