### ISSUE TITLE
Ensure `README.md` contains information about which MPH range

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/toffy#179]
**Is your feature request related to a problem? Please describe.**

The `README.md` doesn't contain info about how the range of MPH values needed to indicate the status of the detector. If the values fall out of that range, the user needs to be informed to tune the detector.

**Describe the solution you'd like**

Brief description in section 3 of `README.md` describing this.

**Comment by camisowers** [comment]
@ngreenwald
