### ISSUE TITLE
Ordering of automatically generated TMA FOV names

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/toffy#18]
Currently, the names of the automatically generated FOV names are sorted in the same order that they are mapped. This makes it difficult to find a given name from a long list of names when trying to update the mapping. 

It would be better if the order of the names as displayed in the update widget was separate from the mapping order, so that they could be sorted alphabetically

**Comment by ngreenwald** [comment]
alphabetical list? text box for entry?

**Comment by alex-l-kong** [comment]
I'm leaning towards a text box for entry. Related to #22, I think we should also implement a text box for the manually-defined FOVs as well. We can discuss at standup today.
