### ISSUE TITLE
Helper function to check for empty json files

### ISSUE THREAD

**Issue by camisowers** [angelolab/toffy#183]
*This is for internal use only; if you'd like to open an issue or request a new feature, please open a bug or enhancement issue*

**Section 1: Design details**

**Relevant background**
Adresses issue #169.
Empty json files, which are produced when a run crashes, interfere with downstream processing.
We want to create a helper function which identifies empty json files and reports this to the user so they can be removed/deleted/recovered as appropriate.

**Design list/flowchart**
Notebooks that will error if empty json files are not deleted.

* 3b extraction in [bin_extraction.py](https://github.com/angelolab/toffy/blob/28ad9a9d93517b43cfbdf9dd777c28129caf3d49/toffy/bin_extraction.py#L19)
     - we will be able to call new helper function within `bin_extraction.extract_missing_fovs()` and remove any empty json fovs from list to be extracted to prevent this
     
* 3c qc & 3d mph notebook cells
     - will get fov list from extracted fov folders instead of bin files 
     - current code shown below
```
# retrieve all the fov names from bin_file_path
fovs = io_utils.remove_file_extensions(io_utils.list_files(bin_file_path, substrs='.bin'))
```

* 4a rosetta & rosetta fine-tuning
     - has an issue because of bin extraction, which will be fixed when issue #180 is addressed.

The watcher notebook may be affected, but the exact behavior is TBD. Will explore later. 

**Required inputs**

`run_dir`: run directory containing FOV json files
`return_json_names = False`: can set to True to return list of empty json file names (i.e. for use in `extract_missing_fovs`)
`warn = True`: will output a warning message to the user that the FOVs were skipped

**Output files**

either return a list of empty json FOV file names or warn the user (or both)

**Section 2: Implementation details**

**Milestones and timeline**

Should have working fixes in a few days, and will test by the end of next week.

**Comment by ngreenwald** [comment]
For 3c, I think we can change the logic to mirror what the watcher does. The current QC notebook extracts each bin file. However, since we'll already have extracted it in 3b, we can modify the behavior to use the `direct` function the watcher does, so that it only runs on extracted tifs

For 3d, we'll need to add the logic in for this helper function.

**Comment by camisowers** [comment]
Sounds good
