### ISSUE TITLE
Notebooks 2a&b

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/toffy#188]
**Is your feature request related to a problem? Please describe.**
Same changes that we've made to the processing notebooks should be made to these. 

Motivation, explanation of how they work, grouping code that needs to be changed together into one cell, etc.

**Comment by ngreenwald** [comment]
The text doesn't show up correctly when running the notebook:
![image](https://user-images.githubusercontent.com/13770365/181933425-eac9f933-3a56-44f6-9b17-e1059f45ab2f.png)

**Comment by alex-l-kong** [comment]
@ngreenwald I'm addressing the documentation issues for `2_tiling` in the currently open PR for adding the interactive tiling scheme in, will apply similar changes to `2_tma`.
