### ISSUE TITLE
Check all notebooks

### ISSUE THREAD

**Issue by camisowers** [angelolab/toffy#192]
**Is your feature request related to a problem? Please describe.**
With the numerous changes to the notebooks in toffy, we need to make sure everything is still working smoothly after all related PRs are merged in.

**Describe the solution you'd like**
We should run through the entire pipeline with sample data to check for unexpected errors and correct functionality, using the actual directories and suggested relative paths.

**Additional context**
* create new test_run folder and copy all necessary files for ~5 FOVs
* test with an additional empty json in bin_file_dir
* test with hidden file
* test with different frameSizePixels values
* Click on all links in all notebooks/readme to make sure they work
+ any other recent implementations we should double check

**Comment by camisowers** [comment]
@angelolab/computational_team

**Comment by srivarra** [comment]
@camisowers Sounds good. Should we run through after all the changes are merged in?

**Comment by camisowers** [comment]
Yes! I'm thinking maybe next Wednesday, but definitely by Friday.

**Comment by ngreenwald** [comment]
Agreed, this can wait till the very last minute

**Comment by alex-l-kong** [comment]
@camisowers agreed, sounds good.

**Comment by camisowers** [comment]
@angelolab/computational_team we'll do this Monday 8/29

**Comment by camisowers** [comment]
Fixes: 
3a: qc metrics plots cropped small
3c: load_imgs_from_tree defualt for comput_qc_metrics is still int16 -> change to float32
4a:     if not os.path.exists(os.path.join(rosetta_image_dir, run)):
                os.makedirs(os.path.join(rosetta_image_dir, run))
