### ISSUE TITLE
Address OOB issues with co-registration and tiling

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/toffy#197]
**Section 1: Design details**

**Relevant background**

Follows up on #141.

The current co-registration process assumes the user inputs the correct values for stage and equivalent optical coordinates. However, this may not always be the case. `1_set_up_toffy.ipynb` should catch these ahead of time.

Additionally, for both tiling notebooks (`2_create_tiled_mibi_run.ipynb` and `2_create_tma_mibi_run.ipynb`), the check needs to extend to the FOVs created for the run file.

**Design overview**

Having verified that the fiducial conversion factors don't drastically differ between Drago and Creed, we can use those as a reference and verify that the generated conversion factors don't get assigned a value more than 20% from those baselines.

Slide boundary references also need to be added to ensure no FOV gets placed outside the slide. This will apply for 2 steps in the tiled region and TMA processes:

- During the verification of the top-left region corners for tiled regions, and the corner FOVs for TMAs
- Generating the FOVs within each tiled region/TMA

**Design list/flowchart**

Basic validation will be handled in the `1_set_up_toffy.ipynb` notebook during both the user input and co-registration param generation cells. If any coordinate or co-registration param falls out of the accepted range for their respective factor, we should report this as an error.

Validating the actual FOVs generated for each tiled region/TMA will be handled in their respective `2_` notebook. For tiled regions, this will happen during both the user input and FOV generation cells. For TMAs, this will happen only during the FOV generation cell (because this masks the call to validate the TMA corners).

**Required inputs**

No more than what's already required for each notebook.

**Output files**

N/A, just a few new error messages to display in case of OOB.

**Section 2: Implementation details**

**Control flow**

`settings.py` will contain constants that define the hard-coded baseline constant conversion factors, as well as the left, right, top, and bottom boundaries of the slide in both stage and optical coordinates.

We'll define 2 helper functions:

1. `verify_coordinate_on_slide`: checks that a coordinate doesn't fall out of the acceptable slide boundary. This will take an argument `coord_type` which can be set to either `'stage'` or `'optical'`
2. `verify_coreg_param_tolerance`: checks that the co-registration parameters don't differ by more than 20% from its acceptable baseline

Both of these functions will throw a `ValueError` if verification fails.

The validating functions will be used by:

1. `generate_coreg_params`: the coordinate validator needs to be run for both stage and optical coordinate inputs. The co-registration parameter validator will verify the final conversion factors generated.
2. `read_tiled_region_inputs`: the coordinate validator runs on the `'centerPointMicrons'` provided for each corner FOV.
3. `generate_tiled_region_fov_list`: before adding a FOV to the list, run the coordinate validator runs on each FOVs `'centerPointMicrons'`.
4. `validate_tma_corners`: add calls to the coordinate validator for each corner
5. `generate_tma_fov_list`: before adding a FOV to the list, run the coordinate validator on each FOV generated
6. Additionally, add a cell in the TMA notebook which loops through each centroid of `manual_fov_regions` and runs them through the coordinate validator. Alternatively, we can encapsulate this using a function in `tiling_utils.py` called `verify_manual_fov_coordinates`

**Milestones and timeline**

1. Implementation (TMA + tiled region): 1-2 days
2. Testing (TMA + tiled region): 2-3 days

**Comment by alex-l-kong** [comment]
@ngreenwald does the design section look good?

**Comment by ngreenwald** [comment]
One other thing I was thinking: Can you look at the range of the co-registration values that are on Creed on Drago, and see how similar the final coefficients are? For example, across the two instruments, if the final regression coefficients are always within 10-20% of some value, we can use that to check and make sure the pairs that the user is providing make sense.

**Comment by alex-l-kong** [comment]
@ngreenwald Creed doesn't have a `coreg_params.json` in `toffy` right now, probably a good idea to run co-registration. Looks like Creed is currently busy being used right now, I'll look into it later.

**Comment by ngreenwald** [comment]
kk, check what time my current run on there is going to end (should be tomorrow AM) and you can do it then.

**Comment by alex-l-kong** [comment]
@ngreenwald just ran co-registration on Creed through Christine's account. The results don't look drastically different from Drago's.

Creed:
- X_MULTIPLIER: 14.421
- X_OFFSET: 27.643
- Y_MULTIPLIER: -14.353
- Y_OFFSET: -77.207

Drago:
- X_MULTIPLIER: 15.679
- X_OFFSET: 24.663
- Y_MULTIPLIER: -15.703
- Y_OFFSET: -75.107

**Comment by ngreenwald** [comment]
Okay great. Lets add a check if anything is more than 20% different from the average of those values

**Comment by alex-l-kong** [comment]
@ngreenwald is it still necessary to check the actual coordinate values assigned to verify they are not OOB, or is it fine to just verify the co-registration conversion factors and have the user re-assign them if they fall out of the acceptable 20% range?

If the latter, then the updated design doc is ready to go. I think verifying the conversion factors should solve our problems because if they're too high, the coordinates will fall OOB anyways (or close enough to the edge of the slide to be considered OOB).

**Comment by ngreenwald** [comment]
Will it add a ton of code to check the individual coordinates? I think checking the actual coordinate is nice because we can raise an error message immediately the user doesn't have to re-enter everything. But if it adds a lot of complexity, then just checking the final coefficients would probably get the job done

**Comment by alex-l-kong** [comment]
@ngreenwald shouldn't be a ton of code, just need to add boundaries in stage coordinates and microns on each side to `settings.py`. In this way, when generating the FOV centroids, we can check if they fall in bounds or not, and throw an error otherwise.

**Comment by alex-l-kong** [comment]
@ngreenwald updated the design doc to account for coordinate checks, let me know what you think.

**Comment by ngreenwald** [comment]
Looks good
