### ISSUE TITLE
Panel conversion helper functions and implementation

### ISSUE THREAD

**Issue by camisowers** [angelolab/toffy#198]
*This is for internal use only; if you'd like to open an issue or request a new feature, please open a bug or enhancement issue*

**Section 1: Design details**

**Relevant background**

Addresses issue #168 and #167.
The format expected for the toffy panel is not quite the same as the one in the provided ionpath file. We want to create helper functions to automatically convert an ionpath panel to a toffy panel. 

**Design overview**

The basis of this change would be to create two new helper functions:
* `convert_panel(panel_path)`: 
<br>1. converts ionpath panel to toffy panel, adding all additional necessary channels listed in the [example panel file](https://github.com/angelolab/toffy/blob/main/files/example_panel_file.csv) <br> 2. copies target and mass columns from original panel, adds `mass_start = mass-0.3` and `mass_stop = mass `columns <br> 3. saves to new csv file `panel_name-toffy.csv`

* `load_panel(panel_path)`:
<br>1. detects whether the provided panel path is to the original or converted panel by checking for `-toffy.csv` <br> 2. if original panel path, check for existence of converted panel and if it can't find it, call `convert_panel()` <br> 3. if converted panel path, load that data <br> 4. return the panel data frame with the appropriate toffy structure

With this functionality, we can simple change what is currently in notebooks 3a, 3b, 3c, 3d
```
panel_path = 'path\to\panel\panel_name.csv'
panel = pd.read_csv(panel_path)
```
to 
```
panel_path = 'path\to\panel\panel_name.csv'
panel = load_panel(panel_path)
```

Also need to edit the [panel_format](https://github.com/angelolab/toffy#panel-format) section of the README.md to explain the panel changes/format. Will link this in notebooks that use the `load_panel` function.

**Required inputs**

full path to panel, which we can get panel name and panel directory from

**Output files**

Will return a pandas data frame in appropriate toffy format. 
Print statements for underlying code process, i.e. "converting ionpath panel to toffy panel, loading panel_name-toffy.csv" or "panel_name-toffy.csv detected in panel_dir, loading panel_name-toffy.csv"

**Section 2: Implementation details**

Once you have completed section 1, please tag the relevant parties and iterate on the initial design details until everyone is satisfied. Then, 
proceed to section 2

**Control flow**

Provide additional, more granular details (if necessary) about how the proposed coding logic will be put together

**Milestones and timeline**

List each of the major components of the project, and provide an estimated completion date for each one.

**Comment by camisowers** [comment]
@ngreenwald

**Comment by ngreenwald** [comment]
Good to go!
