### ISSUE TITLE
Rosetta fine tuning stitching

### ISSUE THREAD

**Issue by benoberlton** [angelolab/toffy#221]
When trying to stitch together fov of rosetta matrix comparisons, an error appears if not all fovs are the same dimension. 
e.g. can't stitch together a 400 fov with an 800.

![image](https://user-images.githubusercontent.com/76409408/185992938-18776eae-4b6c-4cf7-b4c6-7fc9b0bb3118.png)

**Comment by ngreenwald** [comment]
@camisowers, we fixed this in part of the watcher pipeline, can likely just add the same code here to check for different image sizes

**Comment by ngreenwald** [comment]
@benoberlton I used only 800s when testing to get around this issue for now, but it'll be a quick fix

**Comment by camisowers** [comment]
The [get_max_img_size()](https://github.com/angelolab/toffy/blob/31217958d2b6c3429031d3829b402d9e8c6513ae/toffy/image_stitching.py#L11) function currently uses the run file to check for largest image dimensions. I could adapt that to iterate through individual FOV json files as well, however with the removal of bin/json copying in PR #212 that would just become obsolete soon.

I think it's best to address this in a quick PR after the notebooks updates have been merged in.

**Comment by benoberlton** [comment]
@ngreenwald Yeah I ended up just using 800s to get around the issue as well. Just wanted to let it be known just in case.

**Comment by ngreenwald** [comment]
Definitely let us know anytime you find anything weird.

Sounds good Cami, can wait till after the rosetta finetuning merge update
