### ISSUE TITLE
Watcher tempdir cleanup failing in Travis 

### ISSUE THREAD

**Issue by camisowers** [angelolab/toffy#224]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
The travis build fails _sometimes_ because of issues cleaning up the temporary directories on Windows within `fov_watcher_test.py`.

<img width="1167" alt="Screen Shot 2022-08-24 at 5 50 53 PM" src="https://user-images.githubusercontent.com/38049893/186549587-f3211b43-3733-4d05-bfb9-77dcbd086d16.png">

<img width="1177" alt="Screen Shot 2022-08-24 at 5 51 13 PM" src="https://user-images.githubusercontent.com/38049893/186549594-f5b583c5-69e8-4187-8345-1809b2ffb519.png">

@ackagel found this very fun thread where the python creator basically said [c’est la vie](https://bugs.python.org/issue29982) and added an arg to suppress tempfile cleanup errors.

This functionality only exists in python 3.10, so we'll just add our own OSError catch.

**Comment by ngreenwald** [comment]
Are we testing against windows on Travis? Why does this come up?

**Comment by camisowers** [comment]
It's most common on windows but you're right Travis is linux testing. It probably actually has to do with the parallel processing in the watcher tests and permissions to delete tempdirs.
