### ISSUE TITLE
Rosetta explanation in readme

### ISSUE THREAD

**Issue by camisowers** [angelolab/toffy#226]
**Is your feature request related to a problem? Please describe.**

<img width="988" alt="Screen Shot 2022-08-25 at 11 46 24 AM" src="https://user-images.githubusercontent.com/38049893/186744593-db3ba25e-353d-47b7-a4e0-4133de357c4c.png">
Currently there is only a quick explanation in the readme and rosetta notebook about the compensation process. 

**Describe the solution you'd like**
It would be useful to have a more in depth explanation of what exactly we are compensating for and what is in the default matrix, which can then be linked in the notebook for reference.

**Comment by ngreenwald** [comment]
Initially I thought this should go in the readme so it can be linked. However, there's only one notebook that deals with rosetta, so the benefit of having it in the readme (that i can be linked from multiple spots) isn't really relevant. Maybe this should just go in the notebook?

**Comment by camisowers** [comment]
Sounds good to me. I'm currently fixing the image stitching for 4a, so if you send me the description I can just include it in PR #227.

**Comment by ngreenwald** [comment]
"The Rosetta algorithm is used to remove background and noise from image data prior to analysis. It is based on the compensation matrix approach that has been used for correcting flow-cytometry data. The Rosetta matrix contains rows for each of the sources of noise, and columns for each of the output channels. Each entry in the matrix represents the proportional contamination from a given noise channel to a given output channel. 

The majority of the entries in the matrix will never need to be modified. For example, the isotopic impurities present in the elements that are used for conjugation, the proportion of hydride and oxide contamination, and other intrinsic features of the instrument. However, some channels, in particular the "Noodle" channel, which we use to remove organic contamination, can be influenced by sample preparation and instrument configuration. Therefore, this notebook gives the user the opportunity to modify that coefficient."
