### ISSUE TITLE
`list_moly_fovs` needs to ensure encoding method is `'utf-8'`

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/toffy#232]
**Describe the bug**

When the Moly points are being checked, they're being opened without a specified encoding method. This can cause encoding errors.

**Expected behavior**

The JSON should be loaded in correctly.

Explicitly pass an `encoding` argument like `read_json_file`.

**Comment by camisowers** [comment]
<img width="1370" alt="Screen Shot 2022-09-05 at 1 01 25 PM" src="https://user-images.githubusercontent.com/38049893/188697811-59a08e6d-965d-4fd8-a0df-2640a57bd3e2.png">

**Comment by camisowers** [comment]
In this instance the json files were damaged/encoded differently on the user's local computer. I ran the same json files on my computer and the user ran them on their own MIBI computer and it worked fine. 

We can discuss if we should still read each json file with a `utf-8` encoding regardless.
