### ISSUE TITLE
Final cell in 4a compensation notebook returns error/warning and doesn't continue looping through runs

### ISSUE THREAD

**Issue by whitneyt1** [angelolab/toffy#238]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

When running through toffy pipeline on a cohort of six runs with 2 FOVs per run collected in July, the last cell in notebook 4a returns the attached error and stops looping through FOVs. All previous notebooks ran fine and without error. 

<img width="1590" alt="4a_Error-Warning" src="https://user-images.githubusercontent.com/46573884/188700980-1b449652-eecb-46a2-ba00-401a9782fa67.PNG">

**Expected behavior**
We expected the loop to continue to compensate the remaining images. 

**To Reproduce**
Please either copy/paste or screenshot all of the code you ran which produced the error. In addition, copy the full error message.

**Comment by camisowers** [comment]
Hi Whitney! This is because the function is trying to compensate the stitched_images folder as an FOV. We'll get that fixed, but for now you should be able to compensate all your runs by temporarily moving the stitched folder out of your extracted images run folder.
