### ISSUE TITLE
Moly QC point can't be written on windows computer

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/toffy#25]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
The moly QC point includes a special character, the micron symbol, in one of the JSON fields. When this is read in, and then subsequently written to a JSON, it gets reformatted to include a special character, rather than the micron symbol, when used on the CAC. This causes the run JSON file to become improperly formatted. 

**To Reproduce**
Use moly point insertion functionality on CAC

![image](https://user-images.githubusercontent.com/13770365/150477871-d35768d3-cb3d-40bc-8c31-f6b5d0e57d8e.png)

**Comment by ackagel** [comment]
I can check if I'm using `json.load` or `json.loads` here.  If I'm using the former, there's a solid chance the byte representation isn't being converted to utf-8 and is still ascii.  With either one, I think the text encoding (UTF-8) can be specified which would resolve this issue.

**Comment by ngreenwald** [comment]
This is specifically for the TMA validation script, not for parsing bin files

**Comment by ackagel** [comment]
ooooh, gotcha.  It still probably boils down to a text encoding problem in a `json.load(s)` call

**Comment by alex-l-kong** [comment]
I agree with @ackagel, let's try first specifying `encoding='utf8'`, both when we read in the Moly point file and subsequently save the full JSON run file with Moly points inserted.

**Comment by ngreenwald** [comment]
Sounds good
