### ISSUE TITLE
Opening toffy env

### ISSUE THREAD

**Issue by benoberlton** [angelolab/toffy#254]
Currently start_jupyter.sh does not seem to work on the anaconda shell on windows.

![image](https://user-images.githubusercontent.com/76409408/189231083-253da151-ef29-46c5-9bd8-9514ce837d80.png)

However, using the old jupyter lab --allow-root still seems to work.

**Comment by alex-l-kong** [comment]
@benoberlton I was able to run it on Creed, looks like you may be running locally. Can you try using `bash start_jupyter.sh` or `./start_jupyter.sh`?

**Comment by benoberlton** [comment]
Hey Alex, tried this out and got the following:

![image](https://user-images.githubusercontent.com/76409408/189242435-dfc9df69-65b6-4299-8a8e-3137f09c45af.png)

**Comment by alex-l-kong** [comment]
Ok I see. Looks like you may be running into an issue with the script not being Windows compatible. Can you meet over Zoom tomorrow afternoon to discuss this?

**Comment by benoberlton** [comment]
Yup, that works for me. I also tried this on the drago CAC and had the same issue.

Cheers,
Ben






Benjamin Oberlton, B.S.

Ph.D. Candidate | Bendall Lab

Stanford University School of Medicine


________________________________

**Comment by ackagel** [comment]
I think we've actually ran into the second version of the issue before, albeit in a different context.  The issue has to do with the bash script containing character codes that Windows doesn't like (newlines in particular).  The `dos2unix` (or the reverse command `unix2dos`) should be able to translate this so that it plays nice.  I think we have a note about it somewhere in the ark docs; I'll link it once I find it

**Comment by ackagel** [comment]
aqui

https://ark-analysis.readthedocs.io/en/latest/_rtd/windows_setup.html
<img width="729" alt="Screen Shot 2022-09-09 at 2 21 13 PM" src="https://user-images.githubusercontent.com/36260163/189447564-a90e9cad-285d-48dd-96d1-3cd3d8f532ac.png">

**Comment by ngreenwald** [comment]
How come only Ben ran into this issue, and not Alex? How can we change the startup script to be windows-compatible by default? Having everyone run that command on every CAC is not going to work.

**Comment by ackagel** [comment]
Probably just non-standardized bash versions (some which support that \r character, some which don't), if I had to guess.

Regardless, we could run `dos2unix` on the CAC, make sure the 'dos2unix-ified' script works fine, then commit that version in a mini-pr.  I think the character changes/fixes would be preserved.  This would mean that future changes to the `start_jupyter.sh` script would need to be ran through that same step though.

**Comment by alex-l-kong** [comment]
@ngreenwald I met with Ben and we were able to get Drago up and running with the normal `start_jupyter.sh` command.

Ben had some trouble running `start_jupyter.sh` on his local machine with Anaconda Prompt, seems to be an issue with the way he set it up. We'll be communicating separately about that, but seems like the CAC issues have been resolved.

**Comment by ngreenwald** [comment]
Sounds good. If this comes up again then we should commit the modified version since the script is changed so infrequently.
