### ISSUE TITLE
Normilization Loop

### ISSUE THREAD

**Issue by benoberlton** [angelolab/toffy#256]
In book 4b, when running the normilization "generating the necessary normalization files if they weren't already created", most of the fov's ran in ~5min, however after some runs the code eventually seemed to hit a loop. It was still running, but after >20min no new files were made.  I checked to make sure that these runs weren't moly checks and I seem to have all the files for these fovs, so I am guessing this is why I haven't gotten an error. Unsure what the issue is, but can't move forward with this run because im missing the normlization file that needs to be made. I have tried this on a couple of runs and the same stop seems to happen at some fov where the code seems to get stuck.

**Comment by camisowers** [comment]
@benoberlton was able to get the remaining files generated this afternoon with higher RAM on his computer. All the code is working properly and this processing stall shouldn't be an issue on the CAC.
