### ISSUE TITLE
test fov per run error

### ISSUE THREAD

**Issue by benoberlton** [angelolab/toffy#257]
I think there is an error here. We are asked for the # of FOV's that we want per run, but if I choose a # FOVs  > # runs I got the following error. 

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/76409408/189249630-b72100d2-876d-470f-bd8e-6712b14b2294.png">

I was able to fix this by reducing the # FOVs per run to < # runs

**Comment by camisowers** [comment]
I came across this when trying to copy files from a run with a low number of fovs, i.e. f you have a run with only 3 fovs it won't be able to random sample 5. Do you have one run with less than 5 fovs?

Regardless I can change it to a more clear error message if this is the case.

**Comment by benoberlton** [comment]
I had >5 fovs in both I believe, my first run had 9 fovs and the second had 16, I could only get it working if i did <2 fov. Since I only had 2 runs I assumed the issue was there?

**Comment by camisowers** [comment]
The issue was a partial previous image extraction that resulted in only 2 fov folders in one of the runs. So no coding logic needs to be fixed, but again I think giving a more clear error message will avoid this confusion moving forward.

**Comment by ngreenwald** [comment]
Agreed, list the name of the folder that doesn't have enough subfolders
