### ISSUE TITLE
Watcher script

### ISSUE THREAD

**Issue by ackagel** [angelolab/toffy#28]
### **Relevant background**

> Give a brief (1-2 paragraph) description of the problem/issue that this feature is solving, and how it addresses the issue

Some scripts may take awhile to run per FOV.  It would save time if these scripts could be scheduled to run as soon as a FOV was ready for processing.

### **Design overview**

> Describe each of the main components of the proposed project

Primarily a script which can observe a folder.  When a new FOV is added to the folder (json + bin) the script should immediately begin calling user-specified processing functions on that FOV.

### **Design list/flowchart**

>Provide an overview of how the different pieces of the project will interact with each other, either in a numbered list, bullet point, or brief sketch

 1. User specifies folder to watch (should only need run name)
 2. User specifies functions to call/chain on each FOV-completion event
 3. When run, the script parses folder for run json (gets number of fovs, other metadata)
 4. On complete FOV (json + bin), the script runs the specified functions
 5. Watcher function exits once all expected FOVs are complete.

### **Required inputs**

> Provided a description of the required inputs for this project, including column names for dfs, dimensions for image data, prompts for user input, etc

Just a run name (technically a folderpath) for the base script.  For the chained function calls, other inputs might be required depending on the function...

### **Output files**

>Provide a description of the outputs for this project, including column names for dfs, dimensions for image data, etc. If any plots will be generated, provide (simple) sketches demonstrating the plot type and axes labels. 

At a minimum a log file.  Full outputs depend on the specified function callbacks, but generally extracted TIFs, QC metrics, etc.

## **Implementation details**

> Once you have completed section 1, please tag the relevant parties and iterate on the initial design details until everyone is satisfied. Then, proceed to section 2

### **Control flow**

> Provide additional, more granular details (if necessary) about how the proposed coding logic will be put together

### **Milestones and timeline**

> List each of the major components of the project, and provide an estimated completion date for each one.

**Comment by ngreenwald** [comment]
Great, looks good

**Comment by ngreenwald** [comment]
This is what happens when the files are in the process of transferring 
![image](https://user-images.githubusercontent.com/13770365/150881178-868dfa18-7e44-4c23-88e9-605dcfc7ad97.png)

**Comment by ackagel** [comment]
remind me, is the run json transferred over before data aq?

Also, is it possible to generate a checksum/hash of the completed bin/json on the instrument computer before the transfer?  That could be a good way of removing any risk of early file reading/processing.

**Comment by ngreenwald** [comment]
Yes, the run JSON is created immediately at the start of the run. We can assume that it exists already when the watcher script is started. 

There's no easy way to run a check beforehand. However, the errors Erin ran into with corrupted bin files seem to have been fixed, I haven't had any issues. The incomplete transfer can be assessed (I think) by checking if the fov json file has nonzero size.
