### ISSUE TITLE
Rework Rosetta directory structure to support subsequent rounds of compensation

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/toffy#291]
**Relevant background**

Oftentimes, one round of Rosetta will not be enough to remove all unwanted artifacts from an image. Sometimes an additional round of Rosetta will be needed to smooth out specific channels.

The first step is to rework the folder structure of Rosetta to prevent them from blowing up in size. This will also make it easier to navigate the folder to find the relevant files needed.

**Design overview**

The new folder structure will be as follows:

<img width="786" alt="Screen Shot 2022-11-15 at 12 01 09 PM" src="https://user-images.githubusercontent.com/31424707/202014251-4160b70f-fe77-4d72-a199-5d663602fa68.png">

There are a few motivations for this:

- The new Rosetta naming scheme will make it easier to track which matrix was used for which input and output channel(s) are being used. This is important because we'll need to provide users and easy way to distinguish between the v1 and v2 (and potentially multiple v2) matrices.
- Removing the `compensated_data_{mult}` and `stitched_images` folders saves a ton of space. This will be extremely helpful because Creed and Drago reach full capacity otherwise.

**Code mockup**

`create_rosetta_matrices` will need to take in `current_channel_name` and `output_channel_names` (via `generate_rosetta_test_imgs`) to generate the nomenclature needed. The new signature will be:

```
create_rosetta_matrices(default_matrix, save_dir, multipliers, current_channel_name='Noodle', output_channel_name=None, masses=None):
    """Creates a series of compensation matrices for evaluating coefficients
    Args:
        default_matrix (str): path to the rosetta matrix to use as the default
        save_dir (str): output directory
        multipliers (list): the range of values to multiply the default matrix by
            to get new coefficients
        current_channel_name (str):
            channel being adjusted, default Noodle
        output_channel_names (list):
            subset of the channels to compensate for, default None is all
        masses (list | None): an optional list of masses to include in the multiplication. If
            only a subset of masses are specified, other masses will retain their values
            in all iterations. If None, all masses are included
    """
```

The files will now be saved using: 

```
# in the case output_channel is None, it will be set to `all`
mult_matrix.to_csv(os.path.join(save_dir, current_channel_name + '_' + '_'.join(output_channel) + '_' + + '_mult_%s.csv' % (str(i))))
```

Additionally, we'll need to create a helper function to remove the `compensated_image_data` and `stitched_images` folders. We'll create add a function at the end of `generate_rosetta_test_imgs` called `clean_rosetta_dir` with signature:

```
def clean_rosetta_dir(cohort_path: str):
    """Removes extraneous `compensated_image_data` and `stitched_images` folders

    Args:
        cohort_path (str):
            Path to rosetta cohort
    """
```

This function should be called at the end of `compensate_image_data`. However, since this function gets called twice (once for verification, we should add a flag to `compensate_image_data` called `remove_comp_folders` which is by default set to `False`, but we overwrite to `True` on the final call.

**Required inputs**

A summary of the new parameters described above:

- Updated `create_rosetta_matrices`: `current_channel_name` + `output_channel_names`
- Updated `compensate_image_data`: `remove_comp_folders`

No additional files needed.

**Output files**

The nomenclature of the new rosetta matrices is `{src}_{out}_rosetta_matrix_mult_{mult}.csv`.

`compensated_data_{mult}` and `stitched_images` folders will be removed.

**Timeline**
Give a rough estimate for how long you think the project will take. In general, it's better to be too conservative rather than too optimistic. 
- [ ] A couple days
- [X] A week
- [ ] Multiple weeks. For large projects, make sure to agree on a plan that isn't just a single monster PR at the end. 

Estimated date when a fully implemented version will be ready for review:

11/19/22

Estimated date when the finalized project will be merged in:

11/22/22

**Comment by HPiyadasa** [comment]
Looks great!
