### ISSUE TITLE
3a Monitor run notebook does not plot until the end of run

### ISSUE THREAD

**Issue by HPiyadasa** [angelolab/toffy#306]
**Describe the bug**
Watcher script finds the bin files and extracts the tiffs and generates the MPH metrics (found in appropriate dir) but does not **plot** graphs until the run is finished

**Expected behavior**
Plots should be generated (channel stats, MPH plot etc) and updated every time a new FOV is found.

**Comment by HPiyadasa** [comment]
In addition, when/if a run is interrupted halfway on the MIBI scope, start_watcher function will keep watching for new FOVs without generating any plots as a new run will be initiated for the remaining FOVs while the original run json file will never be completed.

**Comment by ngreenwald** [comment]
Maybe adding an additional cell that the user could run in the even that their MIBI run failed, which would trigger all of the run_callbacks.

**Comment by alex-l-kong** [comment]
> In addition, when/if a run is interrupted halfway on the MIBI scope, start_watcher function will keep watching for new FOVs without generating any plots as a new run will be initiated for the remaining FOVs while the original run json file will never be completed.

We should make this a separate issue. I'll open one up.
