### ISSUE TITLE
4a notebook - skip over previously compensated runs

### ISSUE THREAD

**Issue by HPiyadasa** [angelolab/toffy#315]
**Is your feature request related to a problem? Please describe.**
Similar to extract_missing_fovs functions, skip over any runs that have been previously compensated. 

**Describe the solution you'd like**

Something like this

<img width="938" alt="Screenshot 2023-02-05 at 12 51 07 PM" src="https://user-images.githubusercontent.com/62519486/216838911-7362f029-6fb3-444c-9def-b86882ffa4c3.png">

**Comment by ngreenwald** [comment]
I think it's pretty easy to add this logic into the notebook, as you posted. My hesitation is that people won't always want this behavior, and so having the flag in there controlling whether they're skipped or recompensated adds another parameter to keep track of.

**Comment by HPiyadasa** [comment]
True, just that if compensation errors out or kernel dies at any point currently you have to recompensate your whole cohort again even if there is only a few runs remaining. I guess the other aspect is, if the compensation is stopped/crashes mid way through a run, then adding the above code will result in that run being omitted (the remaining FOVs in that run) when continuing.  So would have to check at the fov level.

**Comment by ngreenwald** [comment]
Yup, I agree. I think handling that on a case-by-case basis is better than incorporating the logic into the notebook.
