### ISSUE TITLE
check_detector_voltage function when voltage is 0

### ISSUE THREAD

**Issue by HPiyadasa** [angelolab/toffy#316]
**Describe the bug**
I had a 45 FOV run that crashed after FOV33. However FOV33 was acquired properly (see attached image of HH3/dsDNA (channel 115). There was no issues extracting, compensating this run for all 33 FOVs. 

<img width="1388" alt="Screenshot 2023-02-06 at 1 47 01 PM" src="https://user-images.githubusercontent.com/62519486/217073469-585c400d-6d79-44c9-aaff-a5b087caf970.png">

During normalization notebook, when running check_detector_voltage function, following error occurred

"Between fov-32-scan-1 and fov-33-scan-1 the voltage changed from 2445 to 0." 

When I checked the fov-33-scan-1.json file to check voltage saw the following

{"name":"Detector","currentSetPoint":0}" along with other voltages settings also at 0. 

I manually changed the detector voltage to 2445 in that FOV json file and avoided the error. 

**Expected behavior**
Additional check to see if voltage of FOV is 0, then check fov-xx-scan-1_spectrum.csv file for peak at gold or organics and if above certain threshold do not generate an error. Reasoning - If there was actual signal detected then the detector set to 0 is false so make assumption that FOV has the same detector voltage as rest of run. Give user a warning with what FOV this was and that they should manually inspect this FOV to make sure. Then proceed without erroring out.

**Comment by ngreenwald** [comment]
Same thing here, this adds a lot of additional complex logic (how many counts do we need to see to know that 0 is wrong? which channels? Should we check just this json or multiple?). Given how quick it is to fit the curve once you've already generated the MPH files, I think it's best to raise an error and let the user sort out what went wrong.
