### ISSUE TITLE
MIBItracker API download tests failing

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/toffy#320]
**Describe the bug**

The MIBItracker tests no longer pass. This may be due to changes on the MIBItracker itself.

**Expected behavior**

These tests should either pass, or we should think about removing them.

**To Reproduce**

Run a Travis build for a PR.

**Comment by alex-l-kong** [comment]
@ngreenwald revisiting this, is it fine to remove the tests for the time being? We can still keep the code around for legacy purposes, but I highly doubt anyone's going to be using these moving forward.

**Comment by ngreenwald** [comment]
Yup, seems fine to me
