### ISSUE TITLE
Add min/max values for normalization

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/toffy#324]
**Is your feature request related to a problem? Please describe.**
The current normalization notebook provides a warning if an extreme normalization value is present, but still applies this value. This can result in non-sensical normalization

**Describe the solution you'd like**
We should have a cap for what level of normalization can be applied. Specifically, any normalization value that will result in more than 10x increase in signal should be capped at a 10x increase. Similarly, any normalization value that will result in a decrease in signal should be capped at no change in overall intensity.

**Comment by alex-l-kong** [comment]
@ngreenwald probably need to change up the following warning message:

```
    # check if any values are outside expected range
    extreme_mask = np.logical_or(norm_vals < extreme_vals[0], norm_vals > extreme_vals[1])
    if np.any(extreme_mask):
        bad_channels = np.array(channels)[extreme_mask]
        warnings.warn(
            "The following channel(s) had an extreme normalization "
            "value for fov {}. Manual inspection for accuracy is "
            "recommended: {}".format(fov, bad_channels)
        )
```

I'm thinking we throw this warning only for channels that haven't already been corrected for >10X increase or decrease in normalization.
