### ISSUE TITLE
Extract proficient data to account for NAS bin file deletion

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/toffy#327]
**Relevant background**

The amount of `.bin` files on the NAS is taking up too much space (at >80% capacity, with `.bin` files accounting for at least 60% of that), so we'll need to ensure their removal after a year. However, the information from these `.bin` files should still be maintained on the NAS. One additional important piece of information that will need to be extracted is mass proficient data.

**Design overview**

The main changes to this pipeline concern processes run by both notebooks `3a` (for those running the watcher) and `3b` (for those extracting after a run). This is because both processes call the bin file extraction function.

Currently, the default is to only extract mass-deficient data (-0.3, 0). To extract mass-proficient data, we'll need to run a separate extraction from (0, 0.3). Note that it is not possible to accomplish this by extracting data from (-0.3, 0.3).

With regards the panel files, which contain these integration ranges, these are by default also in mass-deficient ranges. For mass-proficient extraction, we'll need to ensure that these ranges get adjusted accordingly.

**Code mockup**

- _`watcher_callbacks.FovCallbacks` attributes_

A new attribute, `__fov_data_prof: xr.DataArray = field(default=None, init=False)` will need to be added. It is best to maintain a separate variable for the extracted positive data as opposed to just overwriting `__fov_data` itself.

- _`panel_utils.generate_prof_panel`_

This will be a new hidden function to assist with defining the panel for mass-proficient extraction, implemented as such:

```
def generate_prof_panel(panel: pd.DataFrame):
    panel_positive = panel.copy()

    # extract only rows where 'Start' - 'End' = -0.3
    panel_positive_rows = panel_positive[panel_positive['Start'] - panel_positive['End'] == -0.3].index.values

    # explicitly modify the integration range to (0, 0.3)
    panel_positive['Start'] = panel_positive.loc[panel_positive_rows, 'Stop'].copy()
    panel_positive['Stop'] = panel_positive.loc[panel_positive_rows, 'Start'].copy() + 0.3

    return panel_positive
```

- _`watcher_callbacks.FovCallbacks._generate_fov_data`_

This function will need to make a second call to `extract_bin_files` to assign the mass-proficient data to `__fov_data_prof`.  The only changes to make for this call is to set `panel=panel_utils.generate_prof_panel(panel)` and to assign it to `self.__fov_data_prof`.

Note that `panel_utils` is not currently imported in `watcher_callbacks.py`, so this will also need to be added.

- _`watcher_callbacks.FovCallbacks.extract_tiffs`_

The check for `self.__fov_data is None` should also check `self.__fov_data_prof is None` for safety purposes.

This function will need to make a second call to `_write_out` to save the data in `__fov_data_prof`. The only change to make for this call is to set `out_dir=tiff_out_dir + '_proficient'`. This is needed because the data should be written to a separate proficient folder prefixed by the same run name.

- _`watcher_callbacks.generate_pulse_heights`_

We'll need to extract pulse heights for proficient data as well. This will require an additional call to `write_mph_per_mass` inside `generate_pulse_heights`. The call we'll make is:

```
write_mph_per_mass(
    base_dir=self.run_folder,
    output_dir=pulse_out_dir,
    fov=self.point_name,
    masses=panel["Mass"].values,
    start_offset=kwargs.get("mass_start_prof", 0),
    stop_offset=kwargs.get("mass_stop_prof", 0.3),
    proficient=True,
)
```

to ensure the range goes from 0 to 0.3.

Note that folder and file handling is done differently for this function, so a few additional tweaks need to be made inside `normalize.write_mph_per_mass`.

- _`normalize.write_mph_per_mass`_

This function should take another argument called `proficient` of type `bool`. This is simply needed to control the name of the file that gets saved:

```
pulse_heights_file = (
    fov + "_pulse_heights_proficient.csv" if proficient else fov + "_pulse_heights.csv"
)
```

This adds separation between mass deficient and proficient data files.

- _`3b_extract_images_from_bin.ipynb`_

**NOTE: this replaces the previous method where the mass proficient data was extracted in a separate call inside `bin_extraction.extract_missing_fovs`. Needed to change to ensure an easier scheme to account for potentially different missing FOVs inside the deficient and proficient extraction folders.**

An additional call to `extract_missing_fovs` will need to be made on the mass proficient folder. Simply copy the call for the default (mass-deficient) data and add a few changes:

```
extract_missing_fovs(base_dir, extraction_dir + '_proficient', generate_prof_panel(panel))
```
`generate_prof_panel` isn't currently imported by this notebook, so the import statement should be added.

_`4b_normalize_image_data.ipynb`_

If the pulse heights haven't already been extracted by notebook 3a, they get handled in this notebook.

The control flow logic should be modified to 

```
# get all FOVs
fovs = list_folders(os.path.join(rosetta_base_dir, run_name), substrs='fov-')

# loop over each FOV
for fov in fovs:
    # generate mph values
    mph_file_path = os.path.join(mph_run_dir, fov + '_pulse_heights.csv')
    mph_file_path_prof = os.path.join(mph_run_dir, fov + '_pulse_heights_proficient.csv')
    
    # base MPH normalization
    if not os.path.exists(mph_file_path):
        normalize.write_mph_per_mass(base_dir=os.path.join(bin_base_dir, run_name), output_dir=mph_run_dir, 
                                     fov=fov, masses=panel['Mass'].values, start_offset=0.3, stop_offset=0)

    # mass proficient MPH normalization (for long-term storage)
    if not os.path.exists(mph_file_path_prof):
        normalize.write_mph_per_mass(base_dir=os.path.join(bin_base_dir, run_name), output_dir=mph_run_dir, 
                                     fov=fov, masses=panel['Mass'].values, start_offset=0, stop_offset=0.3,
                                     proficient=True)
```

We add another check if the proficient pulse heights file exists or not, and if the latter, create it using the new `start_offset` and `stop_offset`.

**Required inputs**

Same inputs as before.

**Output files**

A new folder, `tiff_out_dir + '_proficient'`, will be created with the mass-proficient images extracted.

**Timeline**

Once I get back from my Europe trip, it should take:

- [ ] A couple days
- [ ] A week
- [X] Multiple weeks. For large projects, make sure to agree on a plan that isn't just a single monster PR at the end. 

Estimated date when a fully implemented version will be ready for review:

4/17 (in Europe from 3/21-4/2)

Estimated date when the finalized project will be merged in:

4/20 (lol)

**Comment by alex-l-kong** [comment]
@ngreenwald let me know how this design doc looks. One question I did have was regarding "extract all potentially relevant antibody/naturally abundant channels" in the original issue. Does this involve extracting all intensities (currently, we only have `'Au'` and `'chan_39'`)? Or is this referring to something else?

**Comment by alex-l-kong** [comment]
@srivarra @camisowers let me know what you think of this too!

**Comment by ngreenwald** [comment]
This looks good. 

- For the proficient panel function, we'll only want to modify masses that go from -0.3 to 0, rather than all masses. 
- The `build_callbacks` function is getting a bit crowded. I don't think we should add in multiple additional callbacks (such as proficient mass, proficient MPH, etc). We should either have proficient generation run silently in the background, or have a single flag the user can pass that will control whether it happens or not. 
- We don't need QC metrics for these images

**Comment by alex-l-kong** [comment]
> This looks good.
> 
> * For the proficient panel function, we'll only want to modify masses that go from -0.3 to 0, rather than all masses.
> * The `build_callbacks` function is getting a bit crowded. I don't think we should add in multiple additional callbacks (such as proficient mass, proficient MPH, etc). We should either have proficient generation run silently in the background, or have a single flag the user can pass that will control whether it happens or not.
> * We don't need QC metrics for these images

- Regarding point #1, just want to clarify an example. Say mass 39 goes from 38.7 to 39. Would this count as an example of a mass that goes from -0.3 to 0 which needs to be modified? 
- Regarding point #2, we're not adding additional callbacks. All the callbacks listed in `watcher_callbacks.py` already exist, we're just modifying existing ones to handle proficient extraction. The only new function that's being added is in `panel_utils`, and that's just a basic helper function.

**Comment by srivarra** [comment]
@alex-l-kong Besides the stuff that Noah mentioned, I have a question about testing the extraction of mass-proficient data. Will we need updated bin files which contain the mass-proficient data?

**Comment by alex-l-kong** [comment]
> @alex-l-kong Besides the stuff that Noah mentioned, I have a question about testing the extraction of mass-proficient data. Will we need updated bin files which contain the mass-proficient data?

The bin files as they are already contain all the information we need. We just need to run a secondary extraction using a different, mass-proficient integration range.

**Comment by camisowers** [comment]
This looks good! I would just note that we should make sure to add checks within the watcher tests to ensure that this data does not get processed beyond the extraction step.

**Comment by alex-l-kong** [comment]
@angelolab/computational_team updated the design doc. Let me know how it looks.
