### ISSUE TITLE
Update tuning curve process for normalization

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/toffy#344]
**Relevant background**

There's been a bit of confusion over normalization curves since outdated ones have been unknowingly used. This has led to issues such as negative values being returned by the normalization notebook.

To address this, the user should now select from one of two normalization curves, with an option to set which one in the notebook.

**Design overview**

Having dedicated tuning curve files means the process of generating it in the setup notebook should be removed.

In the normalization notebook, the user should be provided a flag to choose which tuning curve they wish to use. This flag will then propagate to the actual normalization process, which then pulls the data from the specified tuning curve file.

The tuning curves themselves should be saved in a dedicated folder for ease of access (and not directly in `src`).

**Code mockup**

_Tuning curve files_

**NOTE: file names STC**

The plan is to have two normalization curves: one for default settings (`default_tuning_curve.json`), and one for custom Angelo Lab settings (`angelolab_tuning_curve.json`).

Notebook 1 originally placed these directly in `src/toffy`. It will be better to put these in a dedicated folder in the root `toffy` directory. This folder should be called `tuning_curves`.

_4b_normalize_image_data.ipynb_

Because there are now two normalization curves to choose, the user will need to specify which one they want to use at the beginning of this notebook.

In the cell where `run_name` and `panel_path` get set, include another variable called `tuning_curve_file` that defaults to `default_tuning_curve.json`. Include in the documentation that the user can change this to `angelolab_tuning_curve.json` if they prefer the custom Angelo Lab tuning curve.

The call to `normalize.normalize_image_data` will need to explicitly specify `norm_func_path=os.path.join(.., tuning_curves, tuning_curve_file)`.

_normalize.normalize_image_data_

The default value for `norm_func_path` should be `os.path.join(.., tuning_curves, 'default_tuning_curve.json')`.

_1_set_up_toffy.ipynb_

The entirety of section 3 (`Generate sensitivity curve`) should be nuked.

_normalize.create_tuning_curve_

This function is solely used by section 3 of notebook 1, so it will also be nuked.

**Required inputs**

The user will need to specify which tuning curve to use in notebook 4b.

**Output files**

Same as before.

**Timeline**
Give a rough estimate for how long you think the project will take. In general, it's better to be too conservative rather than too optimistic. 
- [ ] A couple days
- [X] A week
- [ ] Multiple weeks. For large projects, make sure to agree on a plan that isn't just a single monster PR at the end. 

Estimated date when a fully implemented version will be ready for review:

4/13 (dependent on @HPiyadasa in computing the normalization curves, will follow up)

Estimated date when the finalized project will be merged in: 

4/17

**Comment by alex-l-kong** [comment]
@ngreenwald @HPiyadasa let me know if this looks good.

**Comment by alex-l-kong** [comment]
@srivarra @camisowers would love your input too!

**Comment by srivarra** [comment]
@alex-l-kong Looks good! Is the `angelolab_tuning_curve.json` going to change often? Or is it set in stone? Does removing section 3 of notebook 1 imply that https://github.com/angelolab/toffy/blob/a7e67d7ee7975a219a0f16f800b7a34c6ae3b72e/src/toffy/normalize.py#L373-L469 will be removed?

**Comment by alex-l-kong** [comment]
@srivarra yes that's a good point, we'll also be nuking `normalize.create_tuning_function` as well.

**Comment by ngreenwald** [comment]
Instead of deleting that function completely, we should move the code to a different notebook that isn't part of the numbered pipeline. That way, if we need to update it again in the future, the code will be there. 

I think we're actually going to have three tuning curves, not two. But the rest of this logic looks good. We can decide on the names for the curves and the flags once it's all ready.

**Comment by alex-l-kong** [comment]
@ngreenwald sounds good, we can move this to an unnumbered notebook `generate_tuning_curve.ipynb`.

**Comment by camisowers** [comment]
Is the angelo lab tuning curve to account for the specific settings we run the instrument with that are different from the default? Regardless, we should make clear the difference (probably in the readme) so that users aren't wondering why we use a specific one and wonder if they should as well.

**Comment by ngreenwald** [comment]
Yup that's the reason, definitely agree about adding an explanation
