### ISSUE TITLE
Add a pre-commit hook for docstrings

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/toffy#345]
**Is your feature request related to a problem? Please describe.**

The docstrings in `toffy` are inconsistently formatted. It would be nice to include a pre-commit hook that verifies formatting.

**Describe the solution you'd like**

This article lists a few that we could consider: https://towardsdatascience.com/automate-your-python-code-documentation-with-pre-commit-hooks-35c7191949a4. `pydocstyle` looks nice.

**Comment by srivarra** [comment]
@alex-l-kong [`ruff`](https://github.com/charliermarsh/ruff) has some docstring styling. it's implemented in angelolab/maldi_tools.
