### ISSUE TITLE
Watcher freezes randomly

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/toffy#350]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
After multiple new FOVs have been copied over, the watcher sometimes will only process 1, or none, of them. It's not clear what causes this to happen

**Expected behavior**
Consistent processing of new data. 

For example, on Drago, the following run: D:\Data\2023-04-10_panel_check had multiple files copied over at 1PM. However, only the first FOV was processed: C:\Users\Customer.ION\Documents\run_metrics\2023-04-10_panel_check

**Comment by ngreenwald** [comment]
Yesterday's watcher paused again midway through. It still reported new, incorrect files being generated, even though it was stuck after the first few

<img width="1737" alt="image" src="https://user-images.githubusercontent.com/13770365/231519196-2d74cdfd-4699-47a1-8e91-fdcde1f6d606.png">

**Comment by alex-l-kong** [comment]
@ngreenwald this might be related to memory issues, however the `generate_pulse_heights` callback also takes significantly longer than the others, especially for gigantic bin files (10 GB or more).

I've had to leave the 4b notebook running overnight when it calls `write_mph_per_mass` (which calls `generate_pulse_heights`) several times during recent cohort runs to extract pulse heights individually.

**Comment by ngreenwald** [comment]
Yup, that's expected. It's much slower to process the bin file for pulses than to do any of the tiff manipulations, so it takes a long time to do when it's not done in realtime.

**Comment by whitneyt1** [comment]
Hi All! 

I see this is closed, but we've encountered a similar issue where watcher hangs indefinitely. if we're extracting a set of runs and one of them was incomplete (MIBI crashed, ran out of memory, or no autofocus point and FOV was skipped).
