### ISSUE TITLE
Increase stitching flexibility for multiple tiled regions

### ISSUE THREAD

**Issue by camisowers** [angelolab/toffy#351]
*This is for internal use only; if you'd like to open an issue or request a new feature, please open a bug or enhancement issue*

### Instructions
This document should be filled out prior to embarking on any project that will take more than a couple hours to complete. The goal is to make sure that everyone is on the same page for the functionality and requirements of new features. Therefore, it's important that this is detailed enough to catch any misunderstandings beforehand. For larger projects, it can be useful to first give a high-level sketch, and then go back and fill in the details. For smaller ones, filling the entire thing out at once can be sufficient.  

**Relevant background**
Addresses #332.
Our current tiled stitching only accounts for one tiled image per run. We would like the functions instead to allow for any amount of tiles that were generated in a single MIBI run. 
In addition, for runs where the user has included additional points outside of the tiled fovs, those should be ignored for stitching purposes.

**Design overview**

Both [notebook 2a](https://github.com/angelolab/toffy/blob/main/templates/2_create_tiled_mibi_run.ipynb) and the [new tiler](https://github.com/ag-tsai/mibi_tsai) specify tile association by including either a user specified or automatically generated prefix in the custom fov name within the run file. (i.e. Tile_1_R2C3) 

The current logic for tiled image stitching goes through the following steps:
1. check for previous stitching
2. get custom fov names from the run file
   - this needs to be adjusted to ignore any fovs that don’t have `RnCm` format, since right now it just pulls all of them
3. check for prefix in fov names and retrieve the max row and column numbers from the names
   - uses `load_utils.check_fov_name_prefix` and `load_utils.get_tiled_fov_names` from alpineer
   - need to be adjusted to account for more than one prefix
4. load in image data
   - how the `load_utils.load_tiled_img_data` function is used within `toffy.image_stitching.stitch_images` will need to be tweaked so that the image data for each tile is loaded in separately 
5. save stitched channel images in a stitched_images_tiled subfolder
   - within stitched_images_tiled, if there’s more than one tile there will be a subfolder with the tile prefix for each set of stitched images
   - if there’s only one tile, images will be saved directly to the stitched_images_tiled folder

Steps 2-5 will require adjustments, so there will have to be two PRs: one in [alpineer](https://github.com/angelolab/alpineer) and a subsequent one here in toffy. 

**Code mockup**
PSA - There's a lot of nearly complete code down here, mostly just for my benefit so I can really think through the return changes for functions in alpineer before bumping those to toffy.

2: Drop non-tiled fovs from the list of folder names early in `stitch_images()`, so the later helper functions don’t have to deal with it. Any fovs not included in this dictionary are not read in for stitching.
```
def get_tiled_names(fov_list, run_dir):
    """Retrieves the original tiled name for each fov, excludes any non-tiled fovs
    Args:
        fov_list (list): list of fovs that have an existing image dir
        run_dir (str): path to the run directory containing the run json file
    Returns:
        dictionary with RnCm name as keys and the fov-x-scan-1 name as values"""

    run_name = os.path.basename(run_dir)
    run_file_path = os.path.join(run_dir, run_name + ".json")
    fov_names = {}

    # check for a run file
    io_utils.validate_paths(run_file_path)

    # retrieve all tiled fov names
    run_data = json_utils.read_json_file(run_file_path)
    for fov in run_data["fovs"]:
        run_order = fov.get("runOrder")
        default_name = f"fov-{run_order}-scan-1"

        if default_name in fov_list:
            # get tiled name
            tiled_name = fov.get("name")
## UPDATED ##
            # filter out non-tiled and moly fovs
            if re.search(re.compile(r"(R\+?\d+)(C\+?\d+)”), tiled_name) and tiled_name != "MoQC" :
                fov_names[tiled_name] = default_name

    return fov_names
```

3: Currently, `check_fov_name_prefix` returns a tuple consisting of a bool to indicate whether the fov names have a prefix, 
and either a simple list of non-prefixed fov names or a dictionary with the fov names as keys and prefixes as values. 
Instead, we should should just always return a dictionary, with prefixes (or an empty string) as keys and the fovs belonging to each prefix as the values. 
```
def check_fov_name_prefix(fov_list):
    """Checks for a prefix (usually detailing a run name) in any of the provided FOV names

    Args:
        fov_list (list): list of fov name
    Returns:
        (dict): dictionary with prefixes as the keys and fov names as values
    """

     # dict containing fov name and run name
     fov_names = {}
     for folder in fov_list:
         fov = "".join(folder.split("_")[-1:])
         prefix_name = "_".join(folder.split("_")[:-1])
         if prefix_name in fov_names.keys():
            fov_names[prefix_name].append(fov)
         else:
            fov_names[prefix_name] = fov

    return fov_names

```

For `get_tiled_fov_names`, rather than returning a tuple of (fov_names : list , row_num : int, column_num : int), we should instead return a list of tuples in the event there are multiple tiles. Also return the prefix associated with each tuple.
```
def get_tiled_fov_names(fov_list, return_dims=False):
    """Generates the complete tiled fov list when given a list of fov names

    Args:
        fov_list (list):
            list of fov names with are suffixed with RnCm, where n and m are any integer.
        return_dims (bool):
            whether to also return row and col dimensions
    Returns:
        list: list of tuples containing the names of all fovs expected for tiled image shape, if return_dims then also the prefix, row_num and col_num
    """

    expected_tiles = [], [], []

    # check for run name prefixes
    tiled_fov_names = check_fov_name_prefix(fov_list)
    prefixes = tiled_fov_names.keys()
    search_term: re.Pattern = re.compile(r"(R\+?\d+)(C\+?\d+)")

## UPDATED ##
    for tile in prefixes:
       rows, cols, expected_fovs = [], [], []
       fov_names = tiled_fov_names[tile]
       # get tiled image dimensions
       for fov in fov_names:
           R, C = re.search(search_term, fov).group(1, 2)
           rows.append(int(R[1:]))
           cols.append(int(C[1:]))

       row_num, col_num = max(rows), max(cols)

       # fill list of expected fov names
       for n in range(row_num):
           for m in range(col_num):
               fov = f"R{n + 1}C{m + 1}"

               # prepend run names
               if fov in list(fov_names.keys()):
                   expected_fovs.append(f”{tile}_” + fov)
               else:
                   expected_fovs.append(fov)
        
        if return_dims:
           expected_tiles.append(tile, expected_fovs, row_num, col_num)
        else:
           expected_tiles.append(expected_fovs)

   return expected_tiles
```

4/5: We need to load in the fov images for each tile separately and save them in individual folders.

```
def stitch_images(tiff_out_dir, run_dir=None, channels=None, img_sub_folder=None, tiled=False):
    """Creates a new directory containing stitched channel images for the run
    Args:
        tiff_out_dir (str): path to the extracted images for the specific run
        run_dir (str): path to the run directory containing the run json files, default None
        channels (list): list of channels to produce stitched images for, None will do all
        img_sub_folder (str): optional name of image sub-folder within each fov
        tiled (bool): whether to stitch images back into original tiled shape"""

    . . .

    # get load and stitching args
    if tiled:
        # returns a dict with keys RnCm and values og folder names
        folders_dict = get_tiled_names(folders, run_dir)
        try:
            expected_tiles = load_utils.get_tiled_fov_names(
                list(folders_dict.keys()), return_dims=True
            )
        except AttributeError:
            raise ValueError(f"FOV names found in the run file were not in tiled (RnCm) format.")
    else:
        num_cols = math.isqrt(len(folders))
        max_img_size = get_max_img_size(tiff_out_dir, img_sub_folder, run_dir)

    # make stitched subdir
    os.makedirs(stitched_dir)

    # save the stitched images to the stitched_image subdir
    for chan in channels:
        # tiled image loading
## UPDATED ##
           for tile in expected_tiles:
               prefix, expected_fovs, num_rows, num_cols = tile
               if prefix == "":
                     prefix = "unnamed_tile"
               # subset the folders_dict for fovs found in the current tile
               tile_dict = {key: folders_dict[key] for key in expected_fovs} 

               # if multiple tiles, save to individual subdirs
               if len(expected_tiles) > 1:
                  tile_stitched_dir = os.path.join(stitched_dir, prefix)
                  if not os.path.exists(tile_stitched_dir):
                     os.makedirs(tile_stitched_dir)
               else:
                  tile_stitched_dir = stitched_dir

               image_data = load_utils.load_tiled_img_data(
                   tiff_out_dir,
                   tile_dict,
                   expected_fovs,
                   chan,
                   single_dir=False,
                   img_sub_folder=img_sub_folder,
               )
               fname = os.path.join(tile_stitched_dir, chan + "_stitched.tiff")
               stitched = data_utils.stitch_images(image_data, num_cols)
               current_img = stitched.loc["stitched_image", :, :, chan].values
               image_utils.save_image(fname, current_img)
        else:
            image_data = load_utils.load_imgs_from_tree(
                tiff_out_dir,
                img_sub_folder=img_sub_folder,
                fovs=folders,
                channels=[chan],
                max_image_size=max_img_size,
            )
            fname = os.path.join(stitched_dir, chan + "_stitched.tiff")
            stitched = data_utils.stitch_images(image_data, num_cols)
            current_img = stitched.loc["stitched_image", :, :, chan].values
            image_utils.save_image(fname, current_img)
```

*Edit: Will also need to tweak the usage of `load_utils.get_tiled_fov_names` in the `stitch_images_by_shape` in ark. Can wait until later when we bump alpineer in ark.*

**Required inputs**

A mibi run with multiple tiles. Also a run with a single, non-tiled point included.

**Output files**

Separate stitched images for each tile. 

**Timeline**
Give a rough estimate for how long you think the project will take. In general, it's better to be too conservative rather than too optimistic. 
- [ ] A couple days
- [x] A week
- [ ] Multiple weeks. For large projects, make sure to agree on a plan that isn't just a single monster PR at the end. 

Estimated date when a fully implemented version will be ready for review:
Wednesday 4/19

Estimated date when the finalized project will be merged in: 
Friday 4/21

**Comment by alex-l-kong** [comment]
1. We might be able to remove this control statement:

```
# prepend run names
if fov in list(fov_names.keys()):
    expected_fovs.append(f”{tile}_” + fov)
else:
    expected_fovs.append(fov)
```

becomes just

```
expected_fovs.append(f"{tile}_" + fov)
```

While it's true that not all FOVs generated by this loop will necessarily be contained in the tiled region, not sure ATM if there's a reason prepending the prefix to these "ghost" FOVs will cause issues. That being said, it does provide a good way to distinguish them.

2. Tiny aesthetic modification: we might be able to simplify the regex search for m and n in R{m}C{n}:

```
search_term: re.Pattern = re.compile(r"R\+?(\d+)C\+?(\d+)")
...
R, C = re.search(search_term, fov).group(1, 2)
rows.append(int(R))
cols.append(int(C))
```

3. I think we can should save to individual subdirs even if there is just one tile:

```
# if multiple tiles, save to individual subdirs
if len(expected_tiles) > 1:
    tile_stitched_dir = os.path.join(stitched_dir, prefix)
    if not os.path.exists(tile_stitched_dir):
        os.makedirs(tile_stitched_dir)
else:
    tile_stitched_dir = stitched_dir
```

becomes just

```
tile_stitched_dir = os.path.join(stitched_dir, prefix)
if not os.path.exists(tile_stitched_dir):
    os.makedirs(tile_stitched_dir)
```

**Comment by camisowers** [comment]
Agreed, I think we can just always add the prefix since for those expected fovs without corresponding images, it won't really matter whether the function is checking a math for `Tile_1_R1C4` or `R1C4` since the folder doesn't exist either way.

**Comment by ngreenwald** [comment]
looks good!

**Comment by srivarra** [comment]
Looks good to me. The only thing that I can think of, would be refactoring the regex searching lines for `n` and `m`

```python
def get_r_c(...)
	re.search(re.compile(r"(R\+?\d+)(C\+?\d+)”)
	
	R, C = re.search(search_term, fov).group(1, 2)
	           rows.append(int(R[1:]))
	           cols.append(int(C[1:]))
	return R,C
	
```

since we seem to be using this quite a lot recently.
