### ISSUE TITLE
conda environment fails to build

### ISSUE THREAD

**Issue by bryjcannon** [angelolab/toffy#353]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
conda environment fails to fully build upon initial setup. Specifically, the `jupyter_contrib_nbextensions` package is not found and fails upon environment build. System is Mac (Intel)

**Expected behavior**
Expected toffy_env to build successfully. 

**To Reproduce**
Please either copy/paste or screenshot all of the code you ran which produced the error. In addition, copy the full error message. 
<img width="1165" alt="Screenshot 2023-04-11 at 4 10 30 PM" src="https://user-images.githubusercontent.com/18650480/231308204-9b045429-5acb-4b96-a62d-8d6d2acf8ccf.png">

**Comment by srivarra** [comment]
@bryjcannon `jupyter_conbrib_nbextensions` requires a different channel `conda_forge`.

Run `conda config --add channels conda-forge` in your terminal, and then you should be able to install `toffy` locally.

**Comment by bryjcannon** [comment]
Awesome, thanks. Any way to include this in the environment file in the future? I think Hadeesha had a similar issue after going back and checking slack.

**Comment by srivarra** [comment]
@bryjcannon I've added it to the PR attached above. Give it a quick look.
