### ISSUE TITLE
create_stitched_images callback produces tiffs that are incompatible with photoshop

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/toffy#355]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
The function to generate stitched images makes TIFs that can be opened in imageJ, but show up as blank in photoshop. This is usually because of an issue with the dtype of the tif being saved. 

**Expected behavior**
TIFs that can be opened in photoshop.

**To Reproduce**
Run the stitched images notebook.

**Comment by alex-l-kong** [comment]
Is this happening with the extracted images themselves too, or just the stitched images?

**Comment by ngreenwald** [comment]
Not sure, I assume the extracted images too, but I don't look at those.

**Comment by alex-l-kong** [comment]
I talked with Hadeesha and Inna about this and it's a scaling issue. Dividing the stitched images by 200 (as we do with Rosetta) ensures that they can be viewed in Photoshop. We can add a similar scaling factor here.
