### ISSUE TITLE
Generate MPH per count and MPH per hour plots

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/toffy#38]
**Is your feature request related to a problem? Please describe.**
Right now the MPH plots which are automatically generated have number of FOVs on the x axis. However, this is really just a proxy for amount of imaging time/detector wear and tear. Different FOVs will have different sizes, different amounts of gold, etc. 

**Describe the solution you'd like**
We should explicitly plot the change in MPH as a function of the total number of counts the detector has recieved, and the total amount of time the run has been going for. This will involve adding functions to calculate number of counts per FOV, number of minutes per FOV, and then plot them on a cumulative scale against MPH.

**Comment by camisowers** [comment]
Closed with PR #101
