### ISSUE TITLE
Watcher doesn't execute run callbacks

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/toffy#380]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
On TMA38, the watcher completed successfully. However, image stitching was never performed. 

**Expected behavior**
Run callbacks execute at termination of watcher.

**Comment by alex-l-kong** [comment]
Will have to look into this, running the `watcher_moved` PR on Christine's runs seemed to do the trick. Might be an issue with larger runs?

**Comment by alex-l-kong** [comment]
Tested this issue on some of @ngreenwald's runs, works now.
