### ISSUE TITLE
Clean up watcher output

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/toffy#384]
**Is your feature request related to a problem? Please describe.**
The updated watcher is quite verbose. While useful for testing, this is too much information for a user to figure out if something actually went wrong. 

**Describe the solution you'd like**
Either have a verbose flag, if these messages could be helpful for future debugging, or remove them completely, if the underlying issues have been identified. For default running, only status messages that indicate that something has actually gone wrong should be included, as well as 1 message per FOV saying which one is being processed. 

<img width="867" alt="image" src="https://github.com/angelolab/toffy/assets/13770365/21e162d8-22e1-4e24-bab7-8c5a22d36f78">

**Comment by alex-l-kong** [comment]
@ngreenwald oh this is because I included those print statements specifically on Drago for testing. They're not included in the `main` branch here.

I just updated Drago to point to the `main` branch without the print statements.

**Comment by ngreenwald** [comment]
Got it, sounds good
