### ISSUE TITLE
Identify images partially extracted by watcher

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/toffy#407]
Prior to adding the functionality which re-extracts any images with bin files modified after the JSON, the watcher created partially extracted images. We'll need to go back and identify which FOVs this happened to, and re-extract them

**Comment by alex-l-kong** [comment]
The following FOVs need re-extraction:

- SPAIN TMA40 run 1: FOV60
- SPAIN TMA41 run 1: FOV17, FOV21, FOV29, FOV33
- SPAIN TMA42 run 1: FOV17, FOV38, FOV42
- SPAIN TMA42 run 2: FOV19, FOV20, FOV24
- SPAIN TMA43 run 1: FOV38, FOV50
- SPAIN TMA43 run 2: FOV35, FOV39
- SPAIN TMA44 run 1: FOV19, FOV35, FOV39, FOV48
- SPAIN TMA44 run 2: FOV35, FOV39
- BELLINI TMA25 run 1: FOV15
- BELLINI TMA25 run 2 restart: FOV10 (incomplete), FOV26
- BELLINI TMA26 run 1 restart: FOV15, FOV19, FOV31, FOV37, FOV58
- BELLINI TMA27 run 1: FOV22 (incomplete), FOV24 (incomplete), FOV30
- BELLINI TMA27 run 1 restart: FOV12

**Comment by ngreenwald** [comment]
Great, can you override the SPAIN ones on the NAS? The BELLINI ones are still on the CAC, so updating there should also update on the NAS once it syncs.

**Comment by alex-l-kong** [comment]
All of these FOVs are re-extracted.
