### ISSUE TITLE
Add image overlay to tiled image notebook

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/toffy#42]
**Is your feature request related to a problem? Please describe.**
Currently the user has to estimate how many rows/cols to include in a tiled region based on looking at the slide image. It would be helpful to directly show them how the number of rows/cols they've selected will map onto the tissue

**Describe the solution you'd like**
A simple version of the overlay functionality that exists for the TMA remapping notebook. The user would load an optical image of the slide, and be shown a grid outline of of what the final tiled image will look like

**Comment by alex-l-kong** [comment]
We can definitely do this easily.

On the aesthetic side, if the user specifies multiple tiled regions (ex. 5 or more), the overlay can become a bit involved. There are a couple ways around this:

- Color code each region
- A drop down menu allowing the user to choose the region to overlay

The former would definitely be simpler to implement and use, though the latter would prevent too much traffic in the overlay.

**Comment by alex-l-kong** [comment]
Per our meeting today, we'll keep it color-coded and potentially add interactivity as updates come in.

**Comment by alex-l-kong** [comment]
I believe this is already being addressed by #86. Let me know if there's additional functionality that needs to be added.
