### ISSUE TITLE
Notebook for extracting detector data for autogain testing.

### ISSUE THREAD

**Issue by bryjcannon** [angelolab/toffy#445]
**Is your feature request related to a problem? Please describe.**
Need a notebook to quickly pull out detector voltage info into a) a csv and b) a plot

**Describe the solution you'd like**
I have a notebook `detector_v_plotter` and a src file `fov_detector_calc` that provides this already - just want to integrate this into toffy with the appropriate tests.

**Additional context**
Example csv and plot below.
[detector_gain_values.csv](https://github.com/angelolab/toffy/files/13127359/detector_gain_values.csv)
![detector_gain_plot](https://github.com/angelolab/toffy/assets/18650480/fea7f521-46e3-4ed3-9f20-a3f36c72ecd8)

**Comment by alex-l-kong** [comment]
@bryjcannon we could also add this to the `check_detector_voltage` function that runs in notebook 4b as a QC. Right now, it checks that there's no voltage change. We can add an `autogain` flag in the notebook that, if set, will instead make this plot rather than throw an error.

**Comment by bryjcannon** [comment]
That works for me as long as the outputs (csv and plot in the run metrics folder) are maintained.
