### ISSUE TITLE
Next Release v0.2.2

### ISSUE THREAD

**Issue by srivarra** [angelolab/toffy#446]
**Is your feature request related to a problem? Please describe.**

There are a ton of new features in `toffy` now, so it's time for a new release!

**Describe the solution you'd like**

Update the REAMDE with explicit instructions to install the conda environments.

**Describe alternatives you've considered**
N/A

**Additional context**

Need to wait for the following issues to resolve:
- #447 
- #451

**Comment by camisowers** [comment]
Will you bump seaborn to v0.13 in this PR as well?
It's necessary for correct annotations on the QC metric plots.
