### ISSUE TITLE
Refactor QC metrics to work with watcher function

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/toffy#46]
**Section 1: Design details**

**Is your feature request related to a problem? Please describe.**
The current QC metric notebook/workflow assumes that the user will run it once their run is complete. Moving forward, we want this to be run automatically as part of the watcher script.

**Describe the solution you'd like**
We should refactor QC metrics to work with a watcher function which operates on a single FOV at a time, saving the output.

**Design overview**

The QC metric pipeline consists of 3 parts that will need varying degrees of modification:

1. Download raw images from MIBItracker: this will now be handled by `mibi_bin_tools`. Users will need to specify a path to their `.bin` files and this step will be done on a FOV-by-FOV basis.
2. QC metric extraction: this will also be done on a FOV-by-FOV basis and will append directly to files rather than to in-memory DataFrames. **We will also need to store the run order in a separate file.**
3. QC metric visualization: for now, we'll leave this to run after all the FOVs have been downloaded and QC-extracted. In the future, this may transition to a real-time FOV-by-FOV basis.

**Design list/flowchart**

![watcher_qc drawio](https://user-images.githubusercontent.com/31424707/155206608-64adfc82-932e-4879-b36c-eeb8007e71b3.png)

**Required inputs**

- The path to the bin file folder (contains the MIBI `.bin` files). Each folder will contain a set of files prefixed with the FOV in question. For example, `fov-1-scan-1`.
- **While a bin folder may contain multiple FOVs, only 1 FOV will ever be computed at a time in `compute_qc_metrics`**. The specific FOV that will be computed needs to be passed as an argument to `compute_qc_metrics` from either the watcher script or `example_qc_metrics_comp.ipynb`. **The name of the FOV is defined by the corresponding JSON file (for example, if `fov-1-scan-1.json` is in the folder, the name of the FOV needs to be specified as `fov-1-scan-1`) and not just `fov-1`**.
- The path to the panel file. This defines the integration ranges the bin file needs to extract properly.
- The path to the QC metric folder (contains the `.csv` files for each QC metric per FOV, as well as the FOV run order)
- The path to the visualization folder (contains the `.png` files visualizing each QC metric sorted by run order of FOVs)

**Output files**

The data that gets placed in the QC metric and visualization folders described above.

**Section 2: Implementation details**

**Control flow**

For each QC pipeline step outlined in the `Design overview` portion of Section 1, the corresponding functions will need varying degrees of modification:

1. `compute_qc_metrics` will now compute on just a single FOV per iteration. It will take in an argument `bin_fie_name` which will specify a single FOVs data. Only this FOV will be passed to `mibi_bin_tools.extract_bin_files` with the user-provided bin file folder as `data_dir` without specifying an `out_dir`. The result will be an `xarray.DataArray` containing the channel images for the FOV.
- When calling `extract_bin_files`, the resulting `DataArray` will contain a dimension called `'type'`: for the purposes of this function, this will only contain one coord (`'pulse'`) and is what we'll be subsetting on.

2. To ensure that the watcher script and `example_qc_metrics_comp.ipynb` know which FOVs have been run or not, `compute_qc_metrics` at the end saves a unique file for the FOV passed in with the corresponding QC metric values for each FOV. For non-zero mean intensity, an example file for `fov0` might be called `fov0_nonzero_mean_stats.csv` and look like:

| fov | channel | metric_name |
| ---- | ------ | ----- |
| 'fov0' | chan0 | val1 |
| 'fov0' | chan1 | val2 |
| ... | ... | ... |

We save the data in melted format to make aggregation easier and for visualization purposes. This data will be saved in a specific folder; the path will need to be provided to the function as `qc_dir`.

3. We add an aggregation function, `combine_qc_metrics`, which will simply append all the files for each QC metric together and create one dataset. We can return this as a `pd.DataFrame` or save as a `.csv`, whichever is easier.

4. The watcher script and `example_qc_metrics_comp.ipynb` will worry about which FOVs to pass in. For the latter, the user will need to specify the path to their bin file (called `bin_file_path`) as well as the `qc_dir` they wish to write to. A loop inside the notebook will then check each FOV in `bin_file_path` and see if the corresponding FOV QC metric files exists in `qc_dir`. If they do not, it will pass in that FOV to `compute_qc_metrics` which then runs the QC extraction for that FOV and saves it.
 
5. `visualize_qc_metrics` can stay as is: a `save_dir` can be provided which will store the images created for each metric.

**Milestones and timeline**

1. `mibi_bin_tools` integration: shouldn't take more than 1 day
2. `qc_metric` refactoring: 1 day
3. Testing the updated pipeline: 1-2 days

**Comment by ngreenwald** [comment]
Couple points: 

1. We won't need to store the run order, the FOVs are always named FOV1, FOV2, FOV3, etc by the commercial instrument.
2. This refactored version of the notebook won't need to handle the watcher function logic (which FOV is next, etc). Instead, it will be compatible with the watcher function already having been run on the data. It will loop over each FOV, and check to make sure the FOV-level qc metrics file has already been generated by the watcher. If not, it will generate it. Then at the end it will make the summary plots. 
3. Lets discuss at standup the best way to store the computed data.

**Comment by alex-l-kong** [comment]
Per our discussion today, we'll keep the QC metric writing to 3 separate QC metric files in the folder provided.

**Comment by alex-l-kong** [comment]
Updated the design doc.

**Comment by ngreenwald** [comment]
Looks good. It makes sense to save the plots in a separate qc metrics folder, but I think the individual fov-level csv files can be saved directly in the same directory

**Comment by alex-l-kong** [comment]
Ok, I'll save the fov-level `.csv` files (and the aggregated versions on `combine_qc_metrics` call) in `bin_file_path`.
