### ISSUE TITLE
Speed up rosetta

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/toffy#57]
**Is your feature request related to a problem? Please describe.**
The `_compensate_matrix_simple` function is simple, but slow. This is likely responsible for the majority of the slowness for the overall `compensate_image_data` function. We should look into ways to optimize it, such as by not using broadcasting, parallelizing over channels, etc.

**Comment by alex-l-kong** [comment]
After further testing, decreasing the crop size (ex. from 2048x2048 to 256x256) provides significant speed ups. The complexity to implement the retrieval, processing, and reconstructing of crops will need to be further researched.
