### ISSUE TITLE
links for full builddocs

### ISSUE THREAD

**Issue by ackagel** [angelolab/toffy#61]
links for in depth documentation:
https://docs.conda.io/en/latest/miniconda.html

 https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by ngreenwald** [comment]
@angelolab/computational_team Did this get incorporated already, or still needs to go somewhere?

**Comment by camisowers** [comment]
yes it's in the installation section of the [readme](https://github.com/angelolab/toffy#installation)
