### ISSUE TITLE
Interactive visualization for tiled regions

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/toffy#62]
**Section 1: Design details**

**Relevant background**

Due to the nature of the commercial instrument, the same problem of "deadlocking" (inability to adjust points) will appear for tiled ROIs on a sample as with TMA slides.

For tiling purposes, we need to provide a similar QC step in the TMA tiling process as with tiled region generation. This will involve creating an interactive visualization for users to verify where on the sample they have decided to tile and whether to delete any FOVs in the grid they have defined.

**Design overview**

The step-by-step process on the user's end associated with tasks that need to be addressed:

1. Co-registration: this already exists in `toffy`, it needs to happen for tiled regions over samples as well as TMAs.
2. Generate tiled regions: user will need to provide a tiled region input file defining the top-left corner of each FOV. We can then use the existing notebook to generate the FOVs for each tiled region. This will also handle randomization and Moly point insertion. The end result is a JSON that defines the initial run file.
    i. Erin has requested that we append the ROI identifier for each FOV name. So if there are 3 ROIs, named `'FOV1'`, `'FOV2'`, and `'FOV3'` in the spec file, her scheme will have them named `'FOV1_R1C1'`, `'FOV2_R1C1'`, `'FOV3_R1C1'`, etc. I think this is a nice addition as it will help identify which FOVs belong to which ROIs when visualizing them.
3. Interactive visualization: a lot of this code we can piggyback off of in `toffy`, especially the co-registration scheme. However, we'll need a dedicated function to draw the tiled regions since the following functionality will need to be added:
    i. Color-coding: each ROI should have a different color-coding scheme.
    ii. Ability to delete a FOV: done via a click. Once a FOV is clicked, the FOV will be deleted from the JSON defining the run file.
    iii. To prevent FOVs from overlapping on the image (happens when the ROIs are close to each other), the circles should be drawn small enough.
4. Saving the JSON to the run file: this can be done via a button in the interactive visualization

**Design list/flowchart**

![tiled_region_flowchart drawio (1)](https://user-images.githubusercontent.com/31424707/160034780-ee926d02-7c9d-41e7-8e9e-1ab212e06eeb.png)

**Required inputs**

The following file inputs are needed:

- JSON spec file defining the top-left corners of each ROI to tile on the sample.
    - For each top-left FOV specified, the `centerPointMicrons` field and `fovSizeMicrons` field need to be defined. `centerPointMicrons` defines the centroid of the FOV and `fovSizeMicrons` defines the step size **along the row- and column-axes**.
    - Additionally, the `'name'` field needs to be defined for each top-left FOV. This will define the name of the ROI and the prefix of each FOV in that ROI during the tiling process
    - The user is responsible for ordering the FOVs in the correct ROI order
    - **Note that regardless of the name specified for these top-left FOVs in the spec file, we will treat these as `{ROI_Name}_R1C1`**.
- The path to the Moly point (if Moly point insertion is desired)
- Image defining the sample to be tiled
- Co-registration params file (generated by `update_coregistration_params.ipynb`)
- The name of the location to save the created run file info (in `.json` format)

Additionally, the tiling script already prompts the user to enter the number of FOVs along the row and column axes, as well as the randomization and Moly point insertion settings.

**Output files**

A run file defining the set of FOVs to extract.

**Section 2: Implementation details**

**Control flow**

_Generating the initial run JSON_

The tiling process as currently defined will remain the same, with the potential update of prefixing each fov name with `{ROI_Name}`.

_Interactive visualization updates_

When creating the interactive visualization, we can use the same co-registration as already exists for TMAs. The following additions will need to be made:

- Generate a unique color for each FOV depending on the ROI it belongs to. We can use a discrete colormap for this.
- Add interactivity to the dots indicating FOV labels. The TMA method of using `skimage` to draw the FOV dots directly on the slide will not work. We will need to overlay these dots directly on the image and use `mpl_connect` along with a custom circle drawing class to do this. Examples can be found here: [Matplotlib interactive examples](https://matplotlib.org/stable/users/explain/event_handling.html)
- We can use a similar default radius for each FOV dot on the image, it may need to be larger than for the TMA to account for the `{ROI_Name}` prefix on each FOV (ex. 10)

**Milestones and timeline**

Approximate timeline as follows:

1. Static overlay (2-3 days)
    i. Generating the TMA-like figure for the tiled regions
    ii. Implementing the circle drawing mechanism
    iii. Adding color-coding scheme per ROI
    iv. Potentially renaming the FOVs to include an `{roi_num}` prefix
2. Add dynamic features (1 week)
    i. Use `mpl_connect` to attach event listeners for `on_press` and `on_release`
    ii. Ensure `on_press` stores information about the specific FOV to delete, `on_release` removes the FOV dot from the visualization and from the run file JSON
    iii. Quality control (ex. no extra figures get drawn, each event is attached to the correct FOV dot, ensure the visualization works for different rectangle dimensions
3. Ensure save of run info to `.json` works properly (1 day)
    i. Piggyback off of the save annotation feature implemented for the TMA visualization

**Comment by alex-l-kong** [comment]
@ngreenwald I'm going to begin work on the static overlay tomorrow, I think that should be pretty straightforward since it's just a slightly modified version of the TMA visualization. Let me know if the other parts of the doc look good.

**Comment by ngreenwald** [comment]
I think Erin's idea for naming the FOVs from each ROI makes sense, and can be done independently. How about you start with that one while you wait to hear back from Mike. 

Instead of ROI1_R1C1, I think it makes more sense to name them after whatever the FOV was named defining the upper left hand corner.

**Comment by alex-l-kong** [comment]
@ngreenwald Ok great, updated the design doc let me know if it's good to go.

**Comment by ngreenwald** [comment]
The idea with drawing the tiled regions overlay on the tissue is to visualize what each tile will look like. Since the tiles are squares, we want the overlay to be a square. This should look like someone printed a grid directly on the tissue. The names of individual tiles are not important, so they can be transparent except for a border region, but should show up as flush rectangles of the appropriate size. 

One thing that we should check with the group about next week: if we have 3 different tiled regions, should we only randomize within each ROI, or should we randomize across ROIs as well
