### ISSUE TITLE
Renaming FOV folders

### ISSUE THREAD

**Issue by camisowers** [angelolab/toffy#72]
*This is for internal use only; if you'd like to open an issue or request a new feature, please open a bug or enhancement issue*

**Section 1: Design details**

**Relevant background**

Closes [issue #10](https://github.com/angelolab/toffy/issues/10).
Currently, the FOV folders outputted from MIBI are labeled using a FOV number instead of the name of the specific FOV. (ex: fov-32-scan-1) 
We would like to renamed them to be more informative (ex: MoQC-scan-1).

**Design overview**

Create a helper function to rename the subdirectories using specific FOV names. The FOV names will be retrieved from the metadata in a JSON file, and there are two possible ways this can be done.
  1. Use the run JSON file and iterate through each FOV listed to retrieve the names. 
      - This would rely on the FOVs to be enumerated in the same order they are listed in the run file. 
  2. Retrieve each name from the individual JSON file for that specific FOV.

*Efficiency*
  1. Method 1 requires loading in a much larger file, but since there is a value `scanCount` we can use that to know how many duplicate FOV name folders there are and not have to reread the same FOV name multiple times.
  2. Method 2 uses smaller files, but it is probably less efficient to load every JSON file in the directory. Especially if there are multiple scans, since each scan produces its own folder and JSON file for the same FOV (ex: fov-32-scan-1, fov-32-scan-2, fov-32-scan-3).
     
**Design list/flowchart**

Assuming we can just use the run JSON file (Method 1):
* verify FOV folders are in the path specified
* load the JSON file
* iterate through each FOV listed
    - retrieve `scanCount` and `name`
* verify the name retrieved is valid
* rename the FOV folders accordingly 
    - verify all folder names were changed (the number of FOVs times `scanCount`)

**Required inputs**
The path to the folder containing all of the FOV subfolders (and the JSON file(s) needed). 

**Output files**

The directory names will be overwritten as stated above.

**Section 2: Implementation details**

Once you have completed section 1, please tag the relevant parties and iterate on the initial design details until everyone is satisfied. Then, 
proceed to section 2

**Control flow**

Provide additional, more granular details (if necessary) about how the proposed coding logic will be put together

**Milestones and timeline**

List each of the major components of the project, and provide an estimated completion date for each one.

**Comment by ngreenwald** [comment]
I agree that method 1 makes more sense. However, your example of what to rename to (Au-scan-1) doesn't really make sense. Gold is a single channel, so we wouldn't want an entire FOV to be named that way. Can you take a look at an example FOV and see what some examples of user-provided names are to make sure that part is clear?

**Comment by camisowers** [comment]
Got it.
