### ISSUE TITLE
Generate MPH per count plots

### ISSUE THREAD

**Issue by camisowers** [angelolab/toffy#87]
**Section 1: Design details**

**Relevant background**

Closes #38. 
Current MPH plots produced have evenly spaced FOV numbers on the x-axis (shown below). 
![before_plot](https://user-images.githubusercontent.com/38049893/164771715-e00f51b9-eb7d-4bb4-b6e8-67e6101e66c3.png)
Instead, we want the x-axis to be a cumulative count of overall counts the detector has received, along with making the script watcher compatible.

**Design overview**

This enhancement will create a new jupyter notebook to run necessary checks and compute the new MPH plots. 
The x-axis can be constructed by retrieving `total_counts` for each FOV with the `get_total_counts()` function from mibi-bin-tools.
To make this enhancement watcher compatible, we need to save a csv for each FOV containing the information we need, as well as a complete csv combining all of these values. 

**Design list/flowchart**

* Set up appropriate file paths for bin and json files with example data
* Create data frame using `get_total_counts` and `get_median_pulse_height` from mibi-bin-tools
* Save the name/number, total count, and median pulse height in a single csv for each FOV
* Save complete set of values computed to an overall csv
* Visualize MPH plots using matplotlib

**Required inputs**

We'll need the directory containing FOV bin files and json metadata files.

**Output files**

This notebook will output the desired MPH plots. There are a couple of different ways to visualize the new axis:

(a) ![after_xcounts](https://user-images.githubusercontent.com/38049893/164771743-0cfd1fb5-ce63-42a1-9530-a064cf11f8eb.png) (b) ![after_no_num](https://user-images.githubusercontent.com/38049893/164771784-627227cd-236e-4b0b-a366-c87975803c38.png) 
(c) ![after_x](https://user-images.githubusercontent.com/38049893/164771817-7675b86e-9a13-42a2-b886-bd6dad5738fc.png)

Minute differences I know, but I'm partial to (c). Please note any specific formatting details you'd like me to implement. 
I can also add a second plot that adds the regression line. 
![after_x_lm](https://user-images.githubusercontent.com/38049893/164772241-4b53d816-5e93-46d4-9c65-87e19d611e89.png)

**Section 2: Implementation details**

**Milestones and timeline**

Total time = 2 weeks

4/29: Have a functioning notebook that produces plots.
5/2-5/5: Feedback and code tweaking

**Comment by ngreenwald** [comment]
Looks good! Please go ahead and fill out the estimated timeline. 

For the plotting axes, I don't think we need to label number of FOVs at all. Instead, it should show the cumulative counts at evenly spaced intervals. i.e. 5 million, 10 million, 15 million, 20 million, with the fovs plotted as dots wherever they happen to line up
