### ISSUE TITLE
Watcher Callback Chaining

### ISSUE THREAD

**Issue by ackagel** [angelolab/toffy#89]
### **Relevant background**

The watcher script takes a list of callback functions to be run on each FOV as it's discovered by the filesystem.  Currently, each function takes a `run_folder` and a `point_name` argument and performs all operations off of the bin file, which means the bin file may be needlessly re-extracted for each callback.  Further, this limits the scope of the callbacks to rely on the bin file data, as opposed tiff data, cell tables, etc.

A way to preserve relevant information and/or chain callback outputs resolves this issue.

### **Design overview**

The core component of this project is adding an information preserving and/or callback chaining system into the `start_watcher` system.  While there are a few implementation options, the user interface shouldn't be made any more complex, i.e do not require something akin to higher order function usage.

### **Design list/flowchart**

I see two recommendable implementation options here.  I prefer Option 2, but I figured I'd show both.

**Option 1: The Mega Function**

Essentially, have all callback functions exist as arguments/options in one large function.  Chaining/information preservation logic is explicitly written for relevant argument pairings.  Implementation pseudocode:

```
def build_mega_callback(extract_tiffs: bool, generate_qc: bool, do_something_with_qc_data: bool, **kwargs):
    def mega_callback(run_folder: str, point_name: str):
        bin_data = extract_bin(...)
        if extract_tiffs:
            make_tiffs(bin_data, **kwargs)
        if generate_qc:
            qc = make_qc(bin_data, **kwargs)
            if do_something_with_qc_data:
                something_with_qc(qc, **kwargs)
    
    return mega_callback
```

Pros:
 - most 'intention explicit'
 - minimal tweaks to existing codebase

Cons:
 - Probably doesn't scale with callbacks well (too much logic at some point)
 - Could create several different 'mega_callbacks' for different situations, but all would require `extract_tiffs` boilerplate
 - Tests probably scale even worse

**Option 2: "We're not cavemen Spongebob, we have Object Oriented Programming"**

<img src="https://user-images.githubusercontent.com/36260163/165602229-e45b50fe-ee46-4d31-b142-d93c3b2517b9.jpg" width="200" height="300" />

This is similar to the mega function, but uses an object to preserve information.  This allows for more structured chaining logic.  This also makes multiple 'mega_callbacks' viable as the 'extract_tiffs' callback cab be made a base class for others to inherit from.  Implementation pseudocode:

```
# information preserving logic goes here
@dataclass
class FovCallbacks:
    run_folder: str
    point_name: str
    panel: pd.DataFrame = field(None, init=False)
    fov_data: xr.DataArray = field(None, init=False)
    
    def extract_tiffs(self, out_dir: str, panel: pd.DataFrame, **kwargs):
        self.panel = panel
        self.fov_data = extract_bin(...)
        ...
    
    def generate_qc(self, out_dir: str, panel: pd.DataFrame = None, **kwargs):
        if panel == self.panel or panel is None:
            # qc with self.fov_data
            ...
        else:
            # re-extract with new panel
            ...

# this callback building function will not need to be updated
# this is just one way of doing it. there are some cleaner ways that slightly alter user interface
def build_fov_callback(*args, **kwargs):
    def fov_callback(run_folder: str, point_name: str):
        callback_obj = FovCallbacks(run_folder, point_name)
        for arg in args:
            # walrus, python>=3.8
            if cb := getattr(callback_obj, arg, None):
                cb_kwargs = dict((k.split(f'{arg}_')[-1], kwargs[k]) for k in kwargs.keys() if arg in k)
                cb(**kwargs)

    return fov_callback        ​
```

Pros:
 - Very clean/segmented organization
 - Scales well and has intuitive ways of breaking apart related functionality
 - callback assembling logic is largely fixed; code updates (i.e new callbacks + chaining logic) go into class
 - Since functionality is well separated, testing can be well separated as well.

Cons:
 - Cleanest implementation might require some tweaks to the user interface. This would be a dictionary of FovCallback method names as keys, with sub dictionary of argname, argvalue pairs (i.e kwargs).  The example pseudocode uses the existing user interface and is clearly a bit messy.
 - The functional programmer hegemony is displeased by these mutable objects; an offering must be prepared to satiate them.

**Alternative Option**

Just to get it out of the way, there is another option.  We could edit RunStructure and/or FOV_EventHandler to stitch functions together at runtime.  There's several variations to this approach but they're all largely hard to maintain and essentially give RunStructure and/or FOV_EventHandler much more responsibility over data handling + state awareness than they really should ever have.

### **Required inputs**

Callback argument specifications.  This could be a list of method names + all kwargs, or a dictionary of method names to specific kwargs.

### **Output files**

No major change from existing implementation.  Possibly retrieve log file path from FOV_EventHandler and write to log file.

## **Section 2: Implementation details**

see above, lol

**Comment by ackagel** [comment]
@angelolab/computational_team

**Comment by ngreenwald** [comment]
Nice overview. Here's my main question: how does option 2 help simplify the logic between related callbacks?

For example, here: 
<img width="611" alt="image" src="https://user-images.githubusercontent.com/13770365/165630421-3375ce00-fe59-44cf-9372-6158451a157c.png">
The logic within the `generate_qc` function checks if images have been extracted, and if not extracts them again. However, isn't this the same thing that option 1 will do?

Is it the reduction in the number of args that are passed from function to function? Or is something fundamental about having the functions reside within the class that you think helps makes things more clear?

I think the main reason that I'm leaning towards option 1 is that I don't think there's going to be lots of mixing and matching between what callbacks people run. Once we get rosetta integrated in, everyone will enable the rosetta option for their data. Once we get the MPH normalization integrated in, everyone will have that on by default. 

So I view this modular structure more as an easy way for us to slowly add pieces to the pipeline, all of which will run by most users most of the time, rather than an easy way to run only certain parts of this at once.

**Comment by ackagel** [comment]
The logic is pretty much equivalent, with the main difference being organization.  **Option One** would check for data-existence before the actual callback, while **Option Two** can check for data-existence _inside_ the callback i.e each function describes it's own 'run-condition'.

I personally find **Option Two** easier to understand and it to me seems easier to expand, maintain, etc.  That being said, I likely won't be the one maintaining/expanding it though so the preferences of @srivarra and @camisowers would matter more.

In terms of scope, if toffy just stays on the instrument computer, the scaling issue really doesn't apply.  However, if toffy gets moved to the future data storage/processing server, where "on upload" cell-segmentation, (post-run) clustering, fiber-segmentation, etc is desirable, then scaling does become pretty relevant.

**Comment by ngreenwald** [comment]
Okay for sure, sounds good. I think they'll both work fine, so I agree that whichever the future generation likes better is the one we should go with.

**Comment by srivarra** [comment]
I prefer **Option Two**. It might be a bit trickier to get it up and running, but making changes once its working would be easier than the monolithic **Option One**. In addition having each function with it's own set of run conditions will make for an easier time debugging. Personally I prefer using Python with OOD paradigms rather than functional.

**Comment by camisowers** [comment]
Either works for me since I do think that Option One is the more straightforward fix while Option Two has a cleaner organization and potential to be expanded more easily. Depends on future direction really. If @srivarra prefers Option Two that's cool with me.
