### ISSUE TITLE
Watcher log directory not created

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/toffy#97]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
When starting the watcher, the log directory is not created, which leads to an error

**To Reproduce**
![image](https://user-images.githubusercontent.com/13770365/166333539-962ae966-19fa-4411-9dfc-469bd385996d.png)

**Expected behavior**
This looks like another example of the test suite creating folders that the actual function doesn't create, leading to issues. Especially for the watcher, we should be careful about creating folders in the test functions to mask what appear to be bugs in the test logic, when in fact they're actual bugs in the code.

**Comment by ackagel** [comment]
good catch.  I'll have the event handler create the log path on instantiation in the callback chaining pr.  I'll also go through the watcher tests and make sure that there aren't other instances where "non-mocking" folders are created, so that these types of issues are caught.
